import { GITHUB_URL, RELEASES_URL } from "@/lib/links"

function normalizeBasePath(value: string | undefined) {
  if (!value || value === "/") return ""
  return value.endsWith("/") ? value.slice(0, -1) : value
}

export const SITE_NAME = "VoxLabs"
export const SITE_VERSION = "3.0.0"
export const SITE_TAGLINE = "Local-First Desktop Voice Cloning, TTS & Audio Studio"
export const SITE_DESCRIPTION =
  "Ethical AI voice cloning, emotional text-to-speech, script-to-audio, and non-destructive waveform editing in a local-first desktop app for Windows, macOS, and Linux. Powered by Piper, Kokoro 82M, XTTS v2, F5-TTS, and Chatterbox with built-in REST API and MCP server."
export const SITE_KEYWORDS = [
  "VoxLabs",
  "voice cloning",
  "local voice cloning",
  "offline text to speech",
  "TTS desktop app",
  "Kokoro 82M",
  "Piper TTS",
  "Coqui XTTS v2",
  "F5-TTS",
  "Chatterbox TTS",
  "script to audio",
  "non-destructive audio editor",
  "MCP server TTS",
  "ethical AI voice synthesis",
  "emotional speech synthesis",
]

export const LEGAL_EFFECTIVE_DATE = "September 6, 2026"
export const PRIVACY_EMAIL = "privacy@voxlabs.ai"

export function getBasePath() {
  return normalizeBasePath(process.env.NEXT_PUBLIC_BASE_PATH)
}

export function getSiteUrl() {
  const explicit = process.env.NEXT_PUBLIC_SITE_URL?.replace(/\/$/, "")
  if (explicit) return explicit
  const basePath = getBasePath()
  return `https://nishanth-kj.github.io${basePath || "/VoxLabs"}`
}

export function absoluteUrl(path = "/") {
  const base = getSiteUrl()
  if (!path || path === "/") return `${base}/`
  const normalized = path.startsWith("/") ? path : `/${path}`
  if (/\.[a-z0-9]+$/i.test(normalized)) {
    return `${base}${normalized}`
  }
  return `${base}${normalized.endsWith("/") ? normalized : `${normalized}/`}`
}

export const SITE_NAV_PATHS = [
  "/",
  "/docs/",
  "/contribution/",
  "/legal/privacy/",
  "/legal/terms/",
  "/legal/ethics/",
  "/legal/cookies/",
] as const

export const ENGINE_SPECS = [
  {
    name: "Piper (en_US Lessac)",
    type: "Local TTS",
    size: "63 MB",
    compute: "CPU / CUDA",
    highlights: "Fast offline neural speech, zero VRAM required",
  },
  {
    name: "Kokoro 82M",
    type: "Local TTS",
    size: "330 MB",
    compute: "CPU / CUDA (~1 GB VRAM)",
    highlights: "Expressive 82M-parameter model with built-in voices (af_heart, af_bella, bm_george)",
  },
  {
    name: "Coqui XTTS v2",
    type: "Zero-Shot Clone & TTS",
    size: "1.87 GB",
    compute: "CUDA (~4 GB VRAM) / CPU fallback",
    highlights: "Multilingual zero-shot voice cloning from reference samples",
  },
  {
    name: "F5-TTS",
    type: "Zero-Shot Clone & TTS",
    size: "1.35 GB",
    compute: "CUDA (~3 GB VRAM) / CPU fallback",
    highlights: "Flow-matching zero-shot voice cloning with deterministic seed control",
  },
  {
    name: "Chatterbox TTS",
    type: "Zero-Shot Clone & TTS",
    size: "2.10 GB",
    compute: "CUDA (~4 GB VRAM) / CPU fallback",
    highlights: "Native emotion exaggeration, temperature control, and zero-shot cloning",
  },
  {
    name: "VoxLabs DSP & MFCC",
    type: "Audio Enhance & Profile",
    size: "Built-in",
    compute: "CPU",
    highlights: "8-stage DSP chain (denoise, EQ, compressor, de-esser, limiter, BS.1770 LUFS)",
  },
] as const

export const SITE_FAQS = [
  {
    question: "Does VoxLabs run completely offline?",
    answer:
      "Yes. VoxLabs is a local-first native desktop application (PySide6). Local engines—including Piper, Kokoro 82M, Coqui XTTS v2, F5-TTS, and Chatterbox—synthesize speech and clone voices entirely on your computer without uploading audio to the cloud. Online engines (Microsoft Edge Neural and Google TTS) are disabled by default unless explicitly enabled in Settings.",
  },
  {
    question: "Which TTS and voice cloning models does VoxLabs support?",
    answer:
      "VoxLabs supports Piper (63 MB fast CPU TTS), Kokoro 82M (330 MB natural CPU/GPU TTS), Coqui XTTS v2 (multilingual zero-shot cloning), F5-TTS (flow-matching zero-shot cloning), Chatterbox TTS (emotional zero-shot cloning), MFCC pitch-matched voice profiles, and an 8-stage DSP audio enhancement engine.",
  },
  {
    question: "How does VoxLabs enforce ethical voice cloning and speaker consent?",
    answer:
      "Every voice cloning operation requires explicit, attributed consent recording who granted permission and the speaker's name before any audio sample is processed. All generated files are watermarked in metadata with 'AI-generated by VoxLabs'. Revoking consent immediately deletes the speaker's reference samples and voice profile from disk.",
  },
  {
    question: "Can I automate VoxLabs from scripts or AI agents via REST API and MCP?",
    answer:
      "Yes. VoxLabs includes an optional FastAPI server (bound to 127.0.0.1:8942 by default) and a built-in Model Context Protocol (MCP) server available over streamable HTTP (/mcp) and stdio (--stdio). External scripts and AI agents call the exact same TTS, script-to-audio, and audio enhancement services as the desktop UI.",
  },
  {
    question: "Does VoxLabs require a GPU or FFmpeg?",
    answer:
      "Neither is strictly required. Piper and Kokoro 82M run smoothly on a standard CPU, and heavier GPU models (XTTS v2, F5-TTS, Chatterbox) automatically fall back to CPU if CUDA memory is full. WAV, FLAC, OGG, and MP3 work out of the box via libsndfile; FFmpeg on your PATH is only needed for M4A/AAC import and export.",
  },
  {
    question: "What operating systems does VoxLabs support?",
    answer:
      "VoxLabs ships standalone desktop bundles for Windows 10 or later (x64 .zip), macOS 12 or later on Apple silicon (arm64 .dmg), and Linux (Ubuntu 22.04+ / Fedora 39+ x86_64 .tar.gz), and can also be run from source on Python 3.12+ with uv.",
  },
] as const

export const SOFTWARE_JSON_LD = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "Organization",
      "@id": `${getSiteUrl()}/#organization`,
      name: SITE_NAME,
      url: getSiteUrl(),
      sameAs: [GITHUB_URL],
      email: PRIVACY_EMAIL,
    },
    {
      "@type": "WebSite",
      "@id": `${getSiteUrl()}/#website`,
      name: SITE_NAME,
      url: getSiteUrl(),
      description: SITE_DESCRIPTION,
      publisher: { "@id": `${getSiteUrl()}/#organization` },
      inLanguage: "en",
    },
    {
      "@type": "SoftwareApplication",
      "@id": `${getSiteUrl()}/#software`,
      name: SITE_NAME,
      softwareVersion: SITE_VERSION,
      applicationCategory: "MultimediaApplication",
      applicationSubCategory: "AI Voice Cloning, TTS & Audio Production Studio",
      operatingSystem: "Windows 10+, macOS 12+, Linux (Ubuntu 22.04+)",
      softwareRequirements: "Standalone desktop bundle or Python 3.12+; CUDA GPU optional",
      offers: {
        "@type": "Offer",
        price: "0",
        priceCurrency: "USD",
      },
      featureList: [
        "Consent-enforced local AI voice cloning (XTTS v2, F5-TTS, Chatterbox)",
        "Offline neural text-to-speech (Piper, Kokoro 82M) with automatic CPU fallback",
        "Multi-speaker script and lesson to narrated audio with per-section takes",
        "Non-destructive waveform audio editor with instant undo and redo",
        "8-stage DSP enhancement (spectral denoise, RBJ biquad EQ, compressor, de-esser, limiter, BS.1770 LUFS)",
        "Local REST API and Model Context Protocol (MCP) server over HTTP (/mcp) and stdio (--stdio)",
        "Mandatory AI-generated metadata tagging and one-click voice revocation",
      ],
      description: SITE_DESCRIPTION,
      downloadUrl: RELEASES_URL,
      releaseNotes: RELEASES_URL,
      url: getSiteUrl(),
      license: `${GITHUB_URL}/blob/main/LICENSE`,
      author: { "@id": `${getSiteUrl()}/#organization` },
    },
    {
      "@type": "HowTo",
      "@id": `${getSiteUrl()}/#howto`,
      name: "How to clone a voice and synthesize speech locally with VoxLabs",
      description: "Install the VoxLabs desktop application, record speaker consent, and generate narrated speech offline.",
      step: [
        {
          "@type": "HowToStep",
          position: 1,
          name: "Download and install VoxLabs",
          text: "Download the native VoxLabs desktop bundle for Windows, macOS, or Linux—no cloud account required.",
        },
        {
          "@type": "HowToStep",
          position: 2,
          name: "Record consent and import a voice sample",
          text: "Provide 3 to 30 seconds of clean speech audio and record attributed speaker consent.",
        },
        {
          "@type": "HowToStep",
          position: 3,
          name: "Synthesize speech or render multi-speaker scripts",
          text: "Choose Piper, Kokoro 82M, XTTS v2, F5-TTS, or Chatterbox and adjust emotion, speed, pitch, and pauses.",
        },
        {
          "@type": "HowToStep",
          position: 4,
          name: "Enhance and export locally",
          text: "Edit non-destructively on the waveform timeline, normalize loudness to target LUFS, and export AI-labeled WAV, FLAC, OGG, MP3, or M4A.",
        },
      ],
    },
    {
      "@type": "FAQPage",
      "@id": `${getSiteUrl()}/#faq`,
      mainEntity: SITE_FAQS.map((item) => ({
        "@type": "Question",
        name: item.question,
        acceptedAnswer: {
          "@type": "Answer",
          text: item.answer,
        },
      })),
    },
  ],
}
