import type { Metadata } from "next"
import { GITHUB_URL, RELEASES_URL } from "@/lib/links"

function normalizeBasePath(value: string | undefined) {
  if (!value || value === "/") return ""
  return value.endsWith("/") ? value.slice(0, -1) : value
}

export const SITE_NAME = "VoxLabs"
export const SITE_VERSION = "3.0.0"
export const SITE_TAGLINE = "Local-First Desktop Voice Cloning, TTS & Audio Studio"
// Meta description: search results cut it off after ~155 characters.
export const SITE_DESCRIPTION =
  "Free, open-source desktop app for consent-based AI voice cloning, offline text-to-speech, script-to-audio and audio editing on Windows, macOS and Linux."
// The full summary, for structured data and AI assistants.
export const SITE_SUMMARY =
  "Ethical AI voice cloning, emotional text-to-speech, script-to-audio, and non-destructive waveform editing in a local-first desktop app for Windows, macOS, and Linux. Powered by Piper, Kokoro 82M, XTTS v2, F5-TTS, and Chatterbox with built-in REST API and MCP server."
export const SITE_KEYWORDS = [
  "VoxLabs",
  "voice cloning",
  "local voice cloning",
  "offline text to speech",
  "TTS desktop app",
  "Kokoro 82M",
  "Piper TTS",
  "Coqui XTTS v2",
  "F5-TTS",
  "Chatterbox TTS",
  "script to audio",
  "non-destructive audio editor",
  "MCP server TTS",
  "ethical AI voice synthesis",
  "emotional speech synthesis",
]

export const LEGAL_EFFECTIVE_DATE = "September 6, 2026"
export const PRIVACY_EMAIL = "privacy@voxlabs.ai"

export function getBasePath() {
  return normalizeBasePath(process.env.NEXT_PUBLIC_BASE_PATH)
}

export function getSiteUrl() {
  const explicit = process.env.NEXT_PUBLIC_SITE_URL?.replace(/\/$/, "")
  if (explicit) return explicit
  const basePath = getBasePath()
  return `https://nishanth-kj.github.io${basePath || "/VoxLabs"}`
}

export function absoluteUrl(path = "/") {
  const base = getSiteUrl()
  if (!path || path === "/") return `${base}/`
  const normalized = path.startsWith("/") ? path : `/${path}`
  if (/\.[a-z0-9]+$/i.test(normalized)) {
    return `${base}${normalized}`
  }
  return `${base}${normalized.endsWith("/") ? normalized : `${normalized}/`}`
}

export const SITE_NAV_PATHS = [
  "/",
  "/docs/",
  "/contribution/",
  "/legal/privacy/",
  "/legal/terms/",
  "/legal/ethics/",
  "/legal/cookies/",
] as const

export const ENGINE_SPECS = [
  {
    name: "Piper (en_US Lessac)",
    type: "Local TTS",
    size: "63 MB",
    compute: "CPU / CUDA",
    highlights: "Fast offline neural speech, zero VRAM required",
  },
  {
    name: "Kokoro 82M",
    type: "Local TTS",
    size: "330 MB",
    compute: "CPU / CUDA (~1 GB VRAM)",
    highlights: "Expressive 82M-parameter model with built-in voices (af_heart, af_bella, bm_george)",
  },
  {
    name: "Coqui XTTS v2",
    type: "Zero-Shot Clone & TTS",
    size: "2.08 GB",
    compute: "CUDA (~4 GB VRAM) / CPU fallback",
    highlights: "Multilingual zero-shot voice cloning from reference samples",
  },
  {
    name: "F5-TTS",
    type: "Zero-Shot Clone & TTS",
    size: "1.40 GB",
    compute: "CUDA (~3 GB VRAM) / CPU fallback",
    highlights: "Flow-matching zero-shot voice cloning with deterministic seed control",
  },
  {
    name: "Chatterbox TTS",
    type: "Zero-Shot Clone & TTS",
    size: "3.20 GB",
    compute: "CUDA (~4 GB VRAM) / CPU fallback",
    highlights: "Native emotion exaggeration, temperature control, and zero-shot cloning",
  },
  {
    name: "VoxLabs DSP & MFCC",
    type: "Audio Enhance & Profile",
    size: "Built-in",
    compute: "CPU",
    highlights: "8-stage DSP chain (denoise, EQ, compressor, de-esser, limiter, BS.1770 LUFS)",
  },
] as const

export const SITE_FAQS = [
  {
    question: "Does VoxLabs run completely offline?",
    answer:
      "Yes. VoxLabs is a local-first native desktop application (PySide6). Local engines—including Piper, Kokoro 82M, Coqui XTTS v2, F5-TTS, and Chatterbox—synthesize speech and clone voices entirely on your computer without uploading audio to the cloud. Online engines (Microsoft Edge Neural and Google TTS) are disabled by default unless explicitly enabled in Settings.",
  },
  {
    question: "Which TTS and voice cloning models does VoxLabs support?",
    answer:
      "VoxLabs supports Piper (63 MB fast CPU TTS), Kokoro 82M (330 MB natural CPU/GPU TTS), Coqui XTTS v2 (multilingual zero-shot cloning), F5-TTS (flow-matching zero-shot cloning), Chatterbox TTS (emotional zero-shot cloning), MFCC pitch-matched voice profiles, and an 8-stage DSP audio enhancement engine.",
  },
  {
    question: "How does VoxLabs enforce ethical voice cloning and speaker consent?",
    answer:
      "Every voice cloning operation requires explicit, attributed consent recording who granted permission and the speaker's name before any audio sample is processed. Every generated file is labeled 'AI-generated by VoxLabs' in its metadata and flagged ai_generated in the local database. Revoking consent immediately deletes the speaker's reference samples and voice profile from disk.",
  },
  {
    question: "Can I automate VoxLabs from scripts or AI agents via REST API and MCP?",
    answer:
      "Yes. VoxLabs includes an optional FastAPI server (bound to 127.0.0.1:8942 by default) and a built-in Model Context Protocol (MCP) server available over streamable HTTP (/mcp) and stdio (--stdio). External scripts and AI agents call the exact same TTS, script-to-audio, and audio enhancement services as the desktop UI.",
  },
  {
    question: "Does VoxLabs require a GPU or FFmpeg?",
    answer:
      "Neither is strictly required. Piper and Kokoro 82M run smoothly on a standard CPU, and heavier GPU models (XTTS v2, F5-TTS, Chatterbox) automatically fall back to CPU if CUDA memory is full. WAV, FLAC, OGG, and MP3 work out of the box via libsndfile; FFmpeg on your PATH is only needed for M4A/AAC import and export.",
  },
  {
    question: "What operating systems does VoxLabs support?",
    answer:
      "VoxLabs ships standalone desktop bundles for Windows 10 or later (x64 .zip), macOS 13 (Ventura) or later on Apple silicon (arm64 .dmg), and Linux (Ubuntu 22.04+ / Fedora 39+ x86_64 .tar.gz), and can also be run from source on Python 3.12+ with uv.",
  },
] as const

const SITE_URL = getSiteUrl()
const ORGANIZATION_ID = `${SITE_URL}/#organization`
const AUTHOR = { "@type": "Person", name: "nishanth-kj", url: "https://github.com/nishanth-kj" }
const LICENSE_URL = `${GITHUB_URL}/blob/main/LICENSE`

export const OG_IMAGE = {
  url: absoluteUrl("/og.jpg"),
  width: 1280,
  height: 720,
  alt: "VoxLabs desktop voice studio",
}

// Plain-text summaries for AI assistants (https://llmstxt.org), linked from every page's <head>.
export const LLMS_TXT_URL = absoluteUrl("/llms.txt")
export const LLMS_FULL_TXT_URL = absoluteUrl("/llms-full.txt")

/** Canonical URL plus Open Graph and Twitter tags, so every page is indexed and shared as itself. */
export function pageMetadata({
  path,
  title,
  description,
}: {
  path: string
  title?: string
  description: string
}): Metadata {
  const url = absoluteUrl(path)
  const shareTitle = title ? `${title} | ${SITE_NAME}` : `${SITE_NAME} — ${SITE_TAGLINE}`
  return {
    ...(title ? { title } : {}),
    description,
    alternates: {
      canonical: url,
      types: { "text/plain": LLMS_TXT_URL, "text/markdown": LLMS_FULL_TXT_URL },
    },
    openGraph: {
      type: "website",
      locale: "en_US",
      url,
      siteName: SITE_NAME,
      title: shareTitle,
      description,
      images: [OG_IMAGE],
    },
    twitter: { card: "summary_large_image", title: shareTitle, description, images: [OG_IMAGE.url] },
  }
}

/** On every page: who publishes the site. */
export const SITE_JSON_LD = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "Organization",
      "@id": ORGANIZATION_ID,
      name: SITE_NAME,
      url: `${SITE_URL}/`,
      logo: absoluteUrl("/icon-512.png"),
      sameAs: [GITHUB_URL],
      email: PRIVACY_EMAIL,
    },
    {
      "@type": "WebSite",
      "@id": `${SITE_URL}/#website`,
      name: SITE_NAME,
      url: `${SITE_URL}/`,
      description: SITE_DESCRIPTION,
      publisher: { "@id": ORGANIZATION_ID },
      inLanguage: "en",
    },
  ],
}

/** On the homepage only: the app, its source, the how-to and the FAQ shown there. */
export const HOME_JSON_LD = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "SoftwareApplication",
      "@id": `${SITE_URL}/#software`,
      name: SITE_NAME,
      softwareVersion: SITE_VERSION,
      applicationCategory: "MultimediaApplication",
      applicationSubCategory: "AI voice cloning, text-to-speech and audio production",
      operatingSystem: "Windows 10+, macOS 13+ (Apple silicon), Linux (Ubuntu 22.04+, Fedora 39+)",
      softwareRequirements: "Standalone desktop bundle, or Python 3.12+ from source; a CUDA GPU is optional",
      isAccessibleForFree: true,
      offers: { "@type": "Offer", price: "0", priceCurrency: "USD" },
      featureList: [
        "Consent-enforced local AI voice cloning (XTTS v2, F5-TTS, Chatterbox)",
        "Offline neural text-to-speech (Piper, Kokoro 82M) with automatic CPU fallback",
        "Multi-speaker script and lesson to narrated audio with per-section takes",
        "Non-destructive waveform audio editor with instant undo and redo",
        "8-stage DSP enhancement (spectral denoise, RBJ biquad EQ, compressor, de-esser, limiter, BS.1770 LUFS)",
        "Local REST API and Model Context Protocol (MCP) server over HTTP (/mcp) and stdio (--stdio)",
        "AI-generated metadata labels on every output and one-click voice revocation",
      ],
      description: SITE_SUMMARY,
      downloadUrl: RELEASES_URL,
      releaseNotes: RELEASES_URL,
      screenshot: OG_IMAGE.url,
      url: `${SITE_URL}/`,
      license: LICENSE_URL,
      author: AUTHOR,
      publisher: { "@id": ORGANIZATION_ID },
    },
    {
      "@type": "SoftwareSourceCode",
      "@id": `${SITE_URL}/#source`,
      name: `${SITE_NAME} source code`,
      codeRepository: GITHUB_URL,
      programmingLanguage: ["Python", "TypeScript"],
      runtimePlatform: "Python 3.12+ (PySide6, FastAPI)",
      license: LICENSE_URL,
      author: AUTHOR,
      targetProduct: { "@id": `${SITE_URL}/#software` },
    },
    {
      "@type": "HowTo",
      "@id": `${SITE_URL}/#howto`,
      name: "How to clone a voice and synthesize speech locally with VoxLabs",
      description:
        "Install the VoxLabs desktop application, record speaker consent, and generate narrated speech offline.",
      step: [
        {
          "@type": "HowToStep",
          position: 1,
          name: "Download and install VoxLabs",
          text: "Download the VoxLabs desktop bundle for Windows, macOS, or Linux from GitHub Releases. No account is required.",
        },
        {
          "@type": "HowToStep",
          position: 2,
          name: "Record consent and import a voice sample",
          text: "Import or record at least 3 seconds (up to 5 minutes) of clean speech; about 30 seconds works well. Record who granted consent and the speaker's name.",
        },
        {
          "@type": "HowToStep",
          position: 3,
          name: "Synthesize speech or render multi-speaker scripts",
          text: "Choose Piper, Kokoro 82M, XTTS v2, F5-TTS, or Chatterbox and adjust emotion, speed, pitch, and pauses.",
        },
        {
          "@type": "HowToStep",
          position: 4,
          name: "Enhance and export locally",
          text: "Edit non-destructively on the waveform, normalize loudness to a target LUFS, and export AI-labeled WAV, FLAC, OGG, or MP3 (M4A with FFmpeg installed).",
        },
      ],
    },
    {
      "@type": "FAQPage",
      "@id": `${SITE_URL}/#faq`,
      mainEntity: SITE_FAQS.map((item) => ({
        "@type": "Question",
        name: item.question,
        acceptedAnswer: { "@type": "Answer", text: item.answer },
      })),
    },
  ],
}

/** Home › … › this page, for subpages. */
export function breadcrumbJsonLd(trail: { name: string; path: string }[]) {
  return {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: [{ name: "Home", path: "/" }, ...trail].map((item, index) => ({
      "@type": "ListItem",
      position: index + 1,
      name: item.name,
      item: absoluteUrl(item.path),
    })),
  }
}
