import { ShieldCheck } from "lucide-react"

export default function EthicsPage() {
    return (
        <div className="min-h-screen bg-background text-foreground pt-32 pb-20 px-6">
            <div className="max-w-3xl mx-auto space-y-8">
                <div className="flex items-center gap-3 mb-8">
                    <ShieldCheck className="w-10 h-10 text-emerald-500" />
                    <h1 className="text-4xl font-bold tracking-tight">Ethical AI Guidelines</h1>
                </div>

                <div className="prose dark:prose-invert max-w-none">
                    <p className="text-muted-foreground text-lg leading-relaxed">
                        VoxLabs is committed to the responsible development and deployment of AI voice technology.
                    </p>

                    <h2 className="text-2xl font-semibold mt-8 mb-4">Consent</h2>
                    <p>
                        We require explicit consent for voice cloning. You may only clone your own voice or a voice for which you have obtained permission.
                    </p>

                    <h2 className="text-2xl font-semibold mt-8 mb-4">Transparency</h2>
                    <p>
                        Content generated by AI should be disclosed as such where appropriate to prevent deception.
                    </p>

                    <h2 className="text-2xl font-semibold mt-8 mb-4">Safety</h2>
                    <p>
                        We implement safeguards to prevent the generation of harmful content, including hate speech and harassment.
                    </p>
                </div>
            </div>
        </div>
    )
}
