"""Fixed audio values: formats, limits, emotion and enhancement presets."""

INTERNAL_FORMAT = "wav"
DEFAULT_SAMPLE_RATE = 24000
SAMPLE_RATES = (16000, 22050, 24000, 44100, 48000)

IMPORT_FORMATS = ("wav", "mp3", "flac", "ogg", "m4a", "aac", "opus")
EXPORT_FORMATS = ("wav", "mp3", "flac", "ogg", "m4a")
# Formats libsndfile writes without FFmpeg (mp3 needs libsndfile >= 1.1).
SOUNDFILE_FORMATS = {"wav": "WAV", "flac": "FLAC", "ogg": "OGG", "mp3": "MP3"}



AI_GENERATED_TAG = "AI-generated by VoxLabs"

# Voice-clone sample requirements
CLONE_MIN_SECONDS = 3.0
CLONE_MAX_SECONDS = 300.0
CLONE_MIN_SAMPLE_RATE = 16000
CLONE_TARGET_SAMPLE_RATE = 24000
SILENCE_THRESHOLD_DB = -40.0
CLIPPING_LEVEL = 0.999

# Script pauses (milliseconds)
PAUSE_SENTENCE_MS = 250
PAUSE_PARAGRAPH_MS = 600
PAUSE_SECTION_MS = 1200

# Emotion presets (ported from the original EmotionalTTSEngine)
EMOTIONS = {
    "neutral": {"speed": 1.0, "pitch": 1.0, "energy": 1.0},
    "happy": {"speed": 1.2, "pitch": 1.1, "energy": 1.2},
    "sad": {"speed": 0.8, "pitch": 0.9, "energy": 0.7},
    "angry": {"speed": 1.3, "pitch": 1.2, "energy": 1.5},
    "calm": {"speed": 0.9, "pitch": 0.95, "energy": 0.8},
    "excited": {"speed": 1.4, "pitch": 1.15, "energy": 1.4},
    "fearful": {"speed": 1.1, "pitch": 1.3, "energy": 0.9},
    "confident": {"speed": 1.0, "pitch": 0.95, "energy": 1.1},
}

# Speaking styles: a speed multiplier and extra pause between sentences.
STYLE_PRESETS = {
    "default": {"speed": 1.0, "pause_ms": 0},
    "narration": {"speed": 0.95, "pause_ms": 100},
    "conversational": {"speed": 1.03, "pause_ms": -80},
    "lecture": {"speed": 0.92, "pause_ms": 150},
    "news": {"speed": 1.05, "pause_ms": 0},
    "storytelling": {"speed": 0.95, "pause_ms": 150},
}
STYLES = tuple(STYLE_PRESETS)

# Longest chunk of text sent to a TTS engine in one call.
TTS_CHUNK_CHARS = 400

# Post-processing / enhancement steps, in pipeline order.
PROCESS_STEPS = (
    "trim_silence",
    "denoise",
    "eq",
    "compress",
    "deess",
    "normalize",
    "limit",
    "loudness",
)
PROCESS_STEP_LABELS = {
    "trim_silence": "Trim silence",
    "denoise": "Denoise",
    "eq": "EQ",
    "compress": "Compress",
    "deess": "De-ess",
    "normalize": "Normalize",
    "limit": "Limiter",
    "loudness": "Loudness",
}

# Enhancement presets: which steps run and their parameters.
ENHANCE_PRESETS = {
    "Raw": {},
    "Voice Clean": {
        "trim_silence": {},
        "denoise": {"strength": 0.6},
        "eq": {"highpass_hz": 80},
        "normalize": {"peak_db": -1.0},
    },
    "Podcast": {
        "trim_silence": {},
        "denoise": {"strength": 0.5},
        "eq": {"highpass_hz": 80, "presence_db": 2.0},
        "compress": {"threshold_db": -20.0, "ratio": 3.0},
        "limit": {"ceiling_db": -1.0},
        "loudness": {"target_lufs": -16.0},
    },
    "Narration": {
        "trim_silence": {},
        "denoise": {"strength": 0.4},
        "eq": {"highpass_hz": 70},
        "compress": {"threshold_db": -22.0, "ratio": 2.5},
        "deess": {},
        "limit": {"ceiling_db": -1.0},
        "loudness": {"target_lufs": -18.0},
    },
    "Lesson": {
        "trim_silence": {},
        "denoise": {"strength": 0.5},
        "eq": {"highpass_hz": 80, "presence_db": 1.5},
        "compress": {"threshold_db": -20.0, "ratio": 3.0},
        "limit": {"ceiling_db": -1.0},
        "loudness": {"target_lufs": -16.0},
    },
    "Studio": {
        "eq": {"highpass_hz": 60, "presence_db": 1.0},
        "compress": {"threshold_db": -18.0, "ratio": 2.0},
        "deess": {},
        "limit": {"ceiling_db": -0.5},
        "loudness": {"target_lufs": -14.0},
    },
}

# Default clean-up applied to freshly generated speech.
DEFAULT_TTS_POST = {"trim_silence": {}, "normalize": {"peak_db": -1.0}}
