"""Built-in speaking voices. Kokoro is the local pack; Edge is the Microsoft neural catalog.

These are preset voices (no samples, no consent). The desktop app creates one row for each
on first launch so they can be edited and used for speech.
"""

KOKORO_VOICES = (
    {'id': 'af_alloy', 'name': 'Kokoro · Alloy (US English)', 'language': 'en', 'description': 'Kokoro built-in voice af_alloy, US English, female.'},
    {'id': 'af_aoede', 'name': 'Kokoro · Aoede (US English)', 'language': 'en', 'description': 'Kokoro built-in voice af_aoede, US English, female.'},
    {'id': 'af_bella', 'name': 'Kokoro · Bella (US English)', 'language': 'en', 'description': 'Kokoro built-in voice af_bella, US English, female.'},
    {'id': 'af_heart', 'name': 'Kokoro · Heart (US English)', 'language': 'en', 'description': 'Kokoro built-in voice af_heart, US English, female.'},
    {'id': 'af_jessica', 'name': 'Kokoro · Jessica (US English)', 'language': 'en', 'description': 'Kokoro built-in voice af_jessica, US English, female.'},
    {'id': 'af_kore', 'name': 'Kokoro · Kore (US English)', 'language': 'en', 'description': 'Kokoro built-in voice af_kore, US English, female.'},
    {'id': 'af_nicole', 'name': 'Kokoro · Nicole (US English)', 'language': 'en', 'description': 'Kokoro built-in voice af_nicole, US English, female.'},
    {'id': 'af_nova', 'name': 'Kokoro · Nova (US English)', 'language': 'en', 'description': 'Kokoro built-in voice af_nova, US English, female.'},
    {'id': 'af_river', 'name': 'Kokoro · River (US English)', 'language': 'en', 'description': 'Kokoro built-in voice af_river, US English, female.'},
    {'id': 'af_sarah', 'name': 'Kokoro · Sarah (US English)', 'language': 'en', 'description': 'Kokoro built-in voice af_sarah, US English, female.'},
    {'id': 'af_sky', 'name': 'Kokoro · Sky (US English)', 'language': 'en', 'description': 'Kokoro built-in voice af_sky, US English, female.'},
    {'id': 'am_adam', 'name': 'Kokoro · Adam (US English)', 'language': 'en', 'description': 'Kokoro built-in voice am_adam, US English, male.'},
    {'id': 'am_echo', 'name': 'Kokoro · Echo (US English)', 'language': 'en', 'description': 'Kokoro built-in voice am_echo, US English, male.'},
    {'id': 'am_eric', 'name': 'Kokoro · Eric (US English)', 'language': 'en', 'description': 'Kokoro built-in voice am_eric, US English, male.'},
    {'id': 'am_fenrir', 'name': 'Kokoro · Fenrir (US English)', 'language': 'en', 'description': 'Kokoro built-in voice am_fenrir, US English, male.'},
    {'id': 'am_liam', 'name': 'Kokoro · Liam (US English)', 'language': 'en', 'description': 'Kokoro built-in voice am_liam, US English, male.'},
    {'id': 'am_michael', 'name': 'Kokoro · Michael (US English)', 'language': 'en', 'description': 'Kokoro built-in voice am_michael, US English, male.'},
    {'id': 'am_onyx', 'name': 'Kokoro · Onyx (US English)', 'language': 'en', 'description': 'Kokoro built-in voice am_onyx, US English, male.'},
    {'id': 'am_puck', 'name': 'Kokoro · Puck (US English)', 'language': 'en', 'description': 'Kokoro built-in voice am_puck, US English, male.'},
    {'id': 'am_santa', 'name': 'Kokoro · Santa (US English)', 'language': 'en', 'description': 'Kokoro built-in voice am_santa, US English, male.'},
    {'id': 'bf_alice', 'name': 'Kokoro · Alice (British English)', 'language': 'en', 'description': 'Kokoro built-in voice bf_alice, British English, female.'},
    {'id': 'bf_emma', 'name': 'Kokoro · Emma (British English)', 'language': 'en', 'description': 'Kokoro built-in voice bf_emma, British English, female.'},
    {'id': 'bf_isabella', 'name': 'Kokoro · Isabella (British English)', 'language': 'en', 'description': 'Kokoro built-in voice bf_isabella, British English, female.'},
    {'id': 'bf_lily', 'name': 'Kokoro · Lily (British English)', 'language': 'en', 'description': 'Kokoro built-in voice bf_lily, British English, female.'},
    {'id': 'bm_daniel', 'name': 'Kokoro · Daniel (British English)', 'language': 'en', 'description': 'Kokoro built-in voice bm_daniel, British English, male.'},
    {'id': 'bm_fable', 'name': 'Kokoro · Fable (British English)', 'language': 'en', 'description': 'Kokoro built-in voice bm_fable, British English, male.'},
    {'id': 'bm_george', 'name': 'Kokoro · George (British English)', 'language': 'en', 'description': 'Kokoro built-in voice bm_george, British English, male.'},
    {'id': 'bm_lewis', 'name': 'Kokoro · Lewis (British English)', 'language': 'en', 'description': 'Kokoro built-in voice bm_lewis, British English, male.'},
    {'id': 'ef_dora', 'name': 'Kokoro · Dora (Spanish)', 'language': 'es', 'description': 'Kokoro built-in voice ef_dora, Spanish, female.'},
    {'id': 'em_alex', 'name': 'Kokoro · Alex (Spanish)', 'language': 'es', 'description': 'Kokoro built-in voice em_alex, Spanish, male.'},
    {'id': 'em_santa', 'name': 'Kokoro · Santa (Spanish)', 'language': 'es', 'description': 'Kokoro built-in voice em_santa, Spanish, male.'},
    {'id': 'ff_siwis', 'name': 'Kokoro · Siwis (French)', 'language': 'fr', 'description': 'Kokoro built-in voice ff_siwis, French, female.'},
    {'id': 'hf_alpha', 'name': 'Kokoro · Alpha (Hindi)', 'language': 'hi', 'description': 'Kokoro built-in voice hf_alpha, Hindi, female.'},
    {'id': 'hf_beta', 'name': 'Kokoro · Beta (Hindi)', 'language': 'hi', 'description': 'Kokoro built-in voice hf_beta, Hindi, female.'},
    {'id': 'hm_omega', 'name': 'Kokoro · Omega (Hindi)', 'language': 'hi', 'description': 'Kokoro built-in voice hm_omega, Hindi, male.'},
    {'id': 'hm_psi', 'name': 'Kokoro · Psi (Hindi)', 'language': 'hi', 'description': 'Kokoro built-in voice hm_psi, Hindi, male.'},
    {'id': 'if_sara', 'name': 'Kokoro · Sara (Italian)', 'language': 'it', 'description': 'Kokoro built-in voice if_sara, Italian, female.'},
    {'id': 'im_nicola', 'name': 'Kokoro · Nicola (Italian)', 'language': 'it', 'description': 'Kokoro built-in voice im_nicola, Italian, male.'},
    {'id': 'jf_alpha', 'name': 'Kokoro · Alpha (Japanese)', 'language': 'ja', 'description': 'Kokoro built-in voice jf_alpha, Japanese, female.'},
    {'id': 'jf_gongitsune', 'name': 'Kokoro · Gongitsune (Japanese)', 'language': 'ja', 'description': 'Kokoro built-in voice jf_gongitsune, Japanese, female.'},
    {'id': 'jf_nezumi', 'name': 'Kokoro · Nezumi (Japanese)', 'language': 'ja', 'description': 'Kokoro built-in voice jf_nezumi, Japanese, female.'},
    {'id': 'jf_tebukuro', 'name': 'Kokoro · Tebukuro (Japanese)', 'language': 'ja', 'description': 'Kokoro built-in voice jf_tebukuro, Japanese, female.'},
    {'id': 'jm_kumo', 'name': 'Kokoro · Kumo (Japanese)', 'language': 'ja', 'description': 'Kokoro built-in voice jm_kumo, Japanese, male.'},
    {'id': 'pf_dora', 'name': 'Kokoro · Dora (Brazilian Portuguese)', 'language': 'pt', 'description': 'Kokoro built-in voice pf_dora, Brazilian Portuguese, female.'},
    {'id': 'pm_alex', 'name': 'Kokoro · Alex (Brazilian Portuguese)', 'language': 'pt', 'description': 'Kokoro built-in voice pm_alex, Brazilian Portuguese, male.'},
    {'id': 'pm_santa', 'name': 'Kokoro · Santa (Brazilian Portuguese)', 'language': 'pt', 'description': 'Kokoro built-in voice pm_santa, Brazilian Portuguese, male.'},
    {'id': 'zf_xiaobei', 'name': 'Kokoro · Xiaobei (Mandarin)', 'language': 'zh', 'description': 'Kokoro built-in voice zf_xiaobei, Mandarin, female.'},
    {'id': 'zf_xiaoni', 'name': 'Kokoro · Xiaoni (Mandarin)', 'language': 'zh', 'description': 'Kokoro built-in voice zf_xiaoni, Mandarin, female.'},
    {'id': 'zf_xiaoxiao', 'name': 'Kokoro · Xiaoxiao (Mandarin)', 'language': 'zh', 'description': 'Kokoro built-in voice zf_xiaoxiao, Mandarin, female.'},
    {'id': 'zf_xiaoyi', 'name': 'Kokoro · Xiaoyi (Mandarin)', 'language': 'zh', 'description': 'Kokoro built-in voice zf_xiaoyi, Mandarin, female.'},
    {'id': 'zm_yunjian', 'name': 'Kokoro · Yunjian (Mandarin)', 'language': 'zh', 'description': 'Kokoro built-in voice zm_yunjian, Mandarin, male.'},
    {'id': 'zm_yunxi', 'name': 'Kokoro · Yunxi (Mandarin)', 'language': 'zh', 'description': 'Kokoro built-in voice zm_yunxi, Mandarin, male.'},
    {'id': 'zm_yunxia', 'name': 'Kokoro · Yunxia (Mandarin)', 'language': 'zh', 'description': 'Kokoro built-in voice zm_yunxia, Mandarin, male.'},
    {'id': 'zm_yunyang', 'name': 'Kokoro · Yunyang (Mandarin)', 'language': 'zh', 'description': 'Kokoro built-in voice zm_yunyang, Mandarin, male.'},
)

EDGE_VOICES = (
    {'id': 'af-ZA-AdriNeural', 'name': 'Edge · Adri (af-ZA)', 'language': 'af', 'description': 'Microsoft Adri Online (Natural) - Afrikaans (South Africa) (female).'},
    {'id': 'af-ZA-WillemNeural', 'name': 'Edge · Willem (af-ZA)', 'language': 'af', 'description': 'Microsoft Willem Online (Natural) - Afrikaans (South Africa) (male).'},
    {'id': 'sq-AL-AnilaNeural', 'name': 'Edge · Anila (sq-AL)', 'language': 'sq', 'description': 'Microsoft Anila Online (Natural) - Albanian (Albania) (female).'},
    {'id': 'sq-AL-IlirNeural', 'name': 'Edge · Ilir (sq-AL)', 'language': 'sq', 'description': 'Microsoft Ilir Online (Natural) - Albanian (Albania) (male).'},
    {'id': 'am-ET-AmehaNeural', 'name': 'Edge · Ameha (am-ET)', 'language': 'am', 'description': 'Microsoft Ameha Online (Natural) - Amharic (Ethiopia) (male).'},
    {'id': 'am-ET-MekdesNeural', 'name': 'Edge · Mekdes (am-ET)', 'language': 'am', 'description': 'Microsoft Mekdes Online (Natural) - Amharic (Ethiopia) (female).'},
    {'id': 'ar-DZ-AminaNeural', 'name': 'Edge · Amina (ar-DZ)', 'language': 'ar', 'description': 'Microsoft Amina Online (Natural) - Arabic (Algeria) (female).'},
    {'id': 'ar-DZ-IsmaelNeural', 'name': 'Edge · Ismael (ar-DZ)', 'language': 'ar', 'description': 'Microsoft Ismael Online (Natural) - Arabic (Algeria) (male).'},
    {'id': 'ar-BH-AliNeural', 'name': 'Edge · Ali (ar-BH)', 'language': 'ar', 'description': 'Microsoft Ali Online (Natural) - Arabic (Bahrain) (male).'},
    {'id': 'ar-BH-LailaNeural', 'name': 'Edge · Laila (ar-BH)', 'language': 'ar', 'description': 'Microsoft Laila Online (Natural) - Arabic (Bahrain) (female).'},
    {'id': 'ar-EG-SalmaNeural', 'name': 'Edge · Salma (ar-EG)', 'language': 'ar', 'description': 'Microsoft Salma Online (Natural) - Arabic (Egypt) (female).'},
    {'id': 'ar-EG-ShakirNeural', 'name': 'Edge · Shakir (ar-EG)', 'language': 'ar', 'description': 'Microsoft Shakir Online (Natural) - Arabic (Egypt) (male).'},
    {'id': 'ar-IQ-BasselNeural', 'name': 'Edge · Bassel (ar-IQ)', 'language': 'ar', 'description': 'Microsoft Bassel Online (Natural) - Arabic (Iraq) (male).'},
    {'id': 'ar-IQ-RanaNeural', 'name': 'Edge · Rana (ar-IQ)', 'language': 'ar', 'description': 'Microsoft Rana Online (Natural) - Arabic (Iraq) (female).'},
    {'id': 'ar-JO-SanaNeural', 'name': 'Edge · Sana (ar-JO)', 'language': 'ar', 'description': 'Microsoft Sana Online (Natural) - Arabic (Jordan) (female).'},
    {'id': 'ar-JO-TaimNeural', 'name': 'Edge · Taim (ar-JO)', 'language': 'ar', 'description': 'Microsoft Taim Online (Natural) - Arabic (Jordan) (male).'},
    {'id': 'ar-KW-FahedNeural', 'name': 'Edge · Fahed (ar-KW)', 'language': 'ar', 'description': 'Microsoft Fahed Online (Natural) - Arabic (Kuwait) (male).'},
    {'id': 'ar-KW-NouraNeural', 'name': 'Edge · Noura (ar-KW)', 'language': 'ar', 'description': 'Microsoft Noura Online (Natural) - Arabic (Kuwait) (female).'},
    {'id': 'ar-LB-LaylaNeural', 'name': 'Edge · Layla (ar-LB)', 'language': 'ar', 'description': 'Microsoft Layla Online (Natural) - Arabic (Lebanon) (female).'},
    {'id': 'ar-LB-RamiNeural', 'name': 'Edge · Rami (ar-LB)', 'language': 'ar', 'description': 'Microsoft Rami Online (Natural) - Arabic (Lebanon) (male).'},
    {'id': 'ar-LY-ImanNeural', 'name': 'Edge · Iman (ar-LY)', 'language': 'ar', 'description': 'Microsoft Iman Online (Natural) - Arabic (Libya) (female).'},
    {'id': 'ar-LY-OmarNeural', 'name': 'Edge · Omar (ar-LY)', 'language': 'ar', 'description': 'Microsoft Omar Online (Natural) - Arabic (Libya) (male).'},
    {'id': 'ar-MA-JamalNeural', 'name': 'Edge · Jamal (ar-MA)', 'language': 'ar', 'description': 'Microsoft Jamal Online (Natural) - Arabic (Morocco) (male).'},
    {'id': 'ar-MA-MounaNeural', 'name': 'Edge · Mouna (ar-MA)', 'language': 'ar', 'description': 'Microsoft Mouna Online (Natural) - Arabic (Morocco) (female).'},
    {'id': 'ar-OM-AbdullahNeural', 'name': 'Edge · Abdullah (ar-OM)', 'language': 'ar', 'description': 'Microsoft Abdullah Online (Natural) - Arabic (Oman) (male).'},
    {'id': 'ar-OM-AyshaNeural', 'name': 'Edge · Aysha (ar-OM)', 'language': 'ar', 'description': 'Microsoft Aysha Online (Natural) - Arabic (Oman) (female).'},
    {'id': 'ar-QA-AmalNeural', 'name': 'Edge · Amal (ar-QA)', 'language': 'ar', 'description': 'Microsoft Amal Online (Natural) - Arabic (Qatar) (female).'},
    {'id': 'ar-QA-MoazNeural', 'name': 'Edge · Moaz (ar-QA)', 'language': 'ar', 'description': 'Microsoft Moaz Online (Natural) - Arabic (Qatar) (male).'},
    {'id': 'ar-SA-HamedNeural', 'name': 'Edge · Hamed (ar-SA)', 'language': 'ar', 'description': 'Microsoft Hamed Online (Natural) - Arabic (Saudi Arabia) (male).'},
    {'id': 'ar-SA-ZariyahNeural', 'name': 'Edge · Zariyah (ar-SA)', 'language': 'ar', 'description': 'Microsoft Zariyah Online (Natural) - Arabic (Saudi Arabia) (female).'},
    {'id': 'ar-SY-AmanyNeural', 'name': 'Edge · Amany (ar-SY)', 'language': 'ar', 'description': 'Microsoft Amany Online (Natural) - Arabic (Syria) (female).'},
    {'id': 'ar-SY-LaithNeural', 'name': 'Edge · Laith (ar-SY)', 'language': 'ar', 'description': 'Microsoft Laith Online (Natural) - Arabic (Syria) (male).'},
    {'id': 'ar-TN-HediNeural', 'name': 'Edge · Hedi (ar-TN)', 'language': 'ar', 'description': 'Microsoft Hedi Online (Natural) - Arabic (Tunisia) (male).'},
    {'id': 'ar-TN-ReemNeural', 'name': 'Edge · Reem (ar-TN)', 'language': 'ar', 'description': 'Microsoft Reem Online (Natural) - Arabic (Tunisia) (female).'},
    {'id': 'ar-AE-FatimaNeural', 'name': 'Edge · Fatima (ar-AE)', 'language': 'ar', 'description': 'Microsoft Fatima Online (Natural) - Arabic (United Arab Emirates) (female).'},
    {'id': 'ar-AE-HamdanNeural', 'name': 'Edge · Hamdan (ar-AE)', 'language': 'ar', 'description': 'Microsoft Hamdan Online (Natural) - Arabic (United Arab Emirates) (male).'},
    {'id': 'ar-YE-MaryamNeural', 'name': 'Edge · Maryam (ar-YE)', 'language': 'ar', 'description': 'Microsoft Maryam Online (Natural) - Arabic (Yemen) (female).'},
    {'id': 'ar-YE-SalehNeural', 'name': 'Edge · Saleh (ar-YE)', 'language': 'ar', 'description': 'Microsoft Saleh Online (Natural) - Arabic (Yemen) (male).'},
    {'id': 'az-AZ-BabekNeural', 'name': 'Edge · Babek (az-AZ)', 'language': 'az', 'description': 'Microsoft Babek Online (Natural) - Azerbaijani (Azerbaijan) (male).'},
    {'id': 'az-AZ-BanuNeural', 'name': 'Edge · Banu (az-AZ)', 'language': 'az', 'description': 'Microsoft Banu Online (Natural) - Azerbaijani (Azerbaijan) (female).'},
    {'id': 'bn-BD-NabanitaNeural', 'name': 'Edge · Nabanita (bn-BD)', 'language': 'bn', 'description': 'Microsoft Nabanita Online (Natural) - Bangla (Bangladesh) (female).'},
    {'id': 'bn-BD-PradeepNeural', 'name': 'Edge · Pradeep (bn-BD)', 'language': 'bn', 'description': 'Microsoft Pradeep Online (Natural) - Bangla (Bangladesh) (male).'},
    {'id': 'bn-IN-BashkarNeural', 'name': 'Edge · Bashkar (bn-IN)', 'language': 'bn', 'description': 'Microsoft Bashkar Online (Natural) - Bangla (India) (male).'},
    {'id': 'bn-IN-TanishaaNeural', 'name': 'Edge · Tanishaa (bn-IN)', 'language': 'bn', 'description': 'Microsoft Tanishaa Online (Natural) - Bengali (India) (female).'},
    {'id': 'bs-BA-VesnaNeural', 'name': 'Edge · Vesna (bs-BA)', 'language': 'bs', 'description': 'Microsoft Vesna Online (Natural) - Bosnian (Bosnia and Herzegovina) (female).'},
    {'id': 'bs-BA-GoranNeural', 'name': 'Edge · Goran (bs-BA)', 'language': 'bs', 'description': 'Microsoft Goran Online (Natural) - Bosnian (Bosnia) (male).'},
    {'id': 'bg-BG-BorislavNeural', 'name': 'Edge · Borislav (bg-BG)', 'language': 'bg', 'description': 'Microsoft Borislav Online (Natural) - Bulgarian (Bulgaria) (male).'},
    {'id': 'bg-BG-KalinaNeural', 'name': 'Edge · Kalina (bg-BG)', 'language': 'bg', 'description': 'Microsoft Kalina Online (Natural) - Bulgarian (Bulgaria) (female).'},
    {'id': 'my-MM-NilarNeural', 'name': 'Edge · Nilar (my-MM)', 'language': 'my', 'description': 'Microsoft Nilar Online (Natural) - Burmese (Myanmar) (female).'},
    {'id': 'my-MM-ThihaNeural', 'name': 'Edge · Thiha (my-MM)', 'language': 'my', 'description': 'Microsoft Thiha Online (Natural) - Burmese (Myanmar) (male).'},
    {'id': 'ca-ES-EnricNeural', 'name': 'Edge · Enric (ca-ES)', 'language': 'ca', 'description': 'Microsoft Enric Online (Natural) - Catalan (male).'},
    {'id': 'ca-ES-JoanaNeural', 'name': 'Edge · Joana (ca-ES)', 'language': 'ca', 'description': 'Microsoft Joana Online (Natural) - Catalan (female).'},
    {'id': 'zh-HK-HiuGaaiNeural', 'name': 'Edge · HiuGaai (zh-HK)', 'language': 'zh', 'description': 'Microsoft HiuGaai Online (Natural) - Chinese (Cantonese Traditional) (female).'},
    {'id': 'zh-HK-HiuMaanNeural', 'name': 'Edge · HiuMaan (zh-HK)', 'language': 'zh', 'description': 'Microsoft HiuMaan Online (Natural) - Chinese (Hong Kong SAR) (female).'},
    {'id': 'zh-HK-WanLungNeural', 'name': 'Edge · WanLung (zh-HK)', 'language': 'zh', 'description': 'Microsoft WanLung Online (Natural) - Chinese (Hong Kong SAR) (male).'},
    {'id': 'zh-CN-XiaoxiaoNeural', 'name': 'Edge · Xiaoxiao (zh-CN)', 'language': 'zh', 'description': 'Microsoft Xiaoxiao Online (Natural) - Chinese (Mainland) (female).'},
    {'id': 'zh-CN-XiaoyiNeural', 'name': 'Edge · Xiaoyi (zh-CN)', 'language': 'zh', 'description': 'Microsoft Xiaoyi Online (Natural) - Chinese (Mainland) (female).'},
    {'id': 'zh-CN-YunjianNeural', 'name': 'Edge · Yunjian (zh-CN)', 'language': 'zh', 'description': 'Microsoft Yunjian Online (Natural) - Chinese (Mainland) (male).'},
    {'id': 'zh-CN-YunxiNeural', 'name': 'Edge · Yunxi (zh-CN)', 'language': 'zh', 'description': 'Microsoft Yunxi Online (Natural) - Chinese (Mainland) (male).'},
    {'id': 'zh-CN-YunxiaNeural', 'name': 'Edge · Yunxia (zh-CN)', 'language': 'zh', 'description': 'Microsoft Yunxia Online (Natural) - Chinese (Mainland) (male).'},
    {'id': 'zh-CN-YunyangNeural', 'name': 'Edge · Yunyang (zh-CN)', 'language': 'zh', 'description': 'Microsoft Yunyang Online (Natural) - Chinese (Mainland) (male).'},
    {'id': 'zh-CN-liaoning-XiaobeiNeural', 'name': 'Edge · Xiaobei (zh-CN-liaoning)', 'language': 'zh', 'description': 'Microsoft Xiaobei Online (Natural) - Chinese (Northeastern Mandarin) (female).'},
    {'id': 'zh-TW-HsiaoChenNeural', 'name': 'Edge · HsiaoChen (zh-TW)', 'language': 'zh', 'description': 'Microsoft HsiaoChen Online (Natural) - Chinese (Taiwan) (female).'},
    {'id': 'zh-TW-YunJheNeural', 'name': 'Edge · YunJhe (zh-TW)', 'language': 'zh', 'description': 'Microsoft YunJhe Online (Natural) - Chinese (Taiwan) (male).'},
    {'id': 'zh-TW-HsiaoYuNeural', 'name': 'Edge · HsiaoYu (zh-TW)', 'language': 'zh', 'description': 'Microsoft HsiaoYu Online (Natural) - Chinese (Taiwanese Mandarin) (female).'},
    {'id': 'zh-CN-shaanxi-XiaoniNeural', 'name': 'Edge · Xiaoni (zh-CN-shaanxi)', 'language': 'zh', 'description': 'Microsoft Xiaoni Online (Natural) - Chinese (Zhongyuan Mandarin Shaanxi) (female).'},
    {'id': 'hr-HR-GabrijelaNeural', 'name': 'Edge · Gabrijela (hr-HR)', 'language': 'hr', 'description': 'Microsoft Gabrijela Online (Natural) - Croatian (Croatia) (female).'},
    {'id': 'hr-HR-SreckoNeural', 'name': 'Edge · Srecko (hr-HR)', 'language': 'hr', 'description': 'Microsoft Srecko Online (Natural) - Croatian (Croatia) (male).'},
    {'id': 'cs-CZ-AntoninNeural', 'name': 'Edge · Antonin (cs-CZ)', 'language': 'cs', 'description': 'Microsoft Antonin Online (Natural) - Czech (Czech) (male).'},
    {'id': 'cs-CZ-VlastaNeural', 'name': 'Edge · Vlasta (cs-CZ)', 'language': 'cs', 'description': 'Microsoft Vlasta Online (Natural) - Czech (Czech) (female).'},
    {'id': 'da-DK-ChristelNeural', 'name': 'Edge · Christel (da-DK)', 'language': 'da', 'description': 'Microsoft Christel Online (Natural) - Danish (Denmark) (female).'},
    {'id': 'da-DK-JeppeNeural', 'name': 'Edge · Jeppe (da-DK)', 'language': 'da', 'description': 'Microsoft Jeppe Online (Natural) - Danish (Denmark) (male).'},
    {'id': 'nl-BE-ArnaudNeural', 'name': 'Edge · Arnaud (nl-BE)', 'language': 'nl', 'description': 'Microsoft Arnaud Online (Natural) - Dutch (Belgium) (male).'},
    {'id': 'nl-BE-DenaNeural', 'name': 'Edge · Dena (nl-BE)', 'language': 'nl', 'description': 'Microsoft Dena Online (Natural) - Dutch (Belgium) (female).'},
    {'id': 'nl-NL-ColetteNeural', 'name': 'Edge · Colette (nl-NL)', 'language': 'nl', 'description': 'Microsoft Colette Online (Natural) - Dutch (Netherlands) (female).'},
    {'id': 'nl-NL-FennaNeural', 'name': 'Edge · Fenna (nl-NL)', 'language': 'nl', 'description': 'Microsoft Fenna Online (Natural) - Dutch (Netherlands) (female).'},
    {'id': 'nl-NL-MaartenNeural', 'name': 'Edge · Maarten (nl-NL)', 'language': 'nl', 'description': 'Microsoft Maarten Online (Natural) - Dutch (Netherlands) (male).'},
    {'id': 'en-AU-WilliamMultilingualNeural', 'name': 'Edge · WilliamMultilingual (en-AU)', 'language': 'en', 'description': 'Microsoft WilliamMultilingual Online (Natural) - English (Australia) (male).'},
    {'id': 'en-AU-NatashaNeural', 'name': 'Edge · Natasha (en-AU)', 'language': 'en', 'description': 'Microsoft Natasha Online (Natural) - English (Australia) (female).'},
    {'id': 'en-CA-ClaraNeural', 'name': 'Edge · Clara (en-CA)', 'language': 'en', 'description': 'Microsoft Clara Online (Natural) - English (Canada) (female).'},
    {'id': 'en-CA-LiamNeural', 'name': 'Edge · Liam (en-CA)', 'language': 'en', 'description': 'Microsoft Liam Online (Natural) - English (Canada) (male).'},
    {'id': 'en-HK-YanNeural', 'name': 'Edge · Yan (en-HK)', 'language': 'en', 'description': 'Microsoft Yan Online (Natural) - English (Hong Kong SAR) (female).'},
    {'id': 'en-HK-SamNeural', 'name': 'Edge · Sam (en-HK)', 'language': 'en', 'description': 'Microsoft Sam Online (Natural) - English (Hongkong) (male).'},
    {'id': 'en-IN-NeerjaExpressiveNeural', 'name': 'Edge · NeerjaExpressive (en-IN)', 'language': 'en', 'description': 'Microsoft Neerja Online (Natural) - English (India) (Preview) (female).'},
    {'id': 'en-IN-NeerjaNeural', 'name': 'Edge · Neerja (en-IN)', 'language': 'en', 'description': 'Microsoft Neerja Online (Natural) - English (India) (female).'},
    {'id': 'en-IN-PrabhatNeural', 'name': 'Edge · Prabhat (en-IN)', 'language': 'en', 'description': 'Microsoft Prabhat Online (Natural) - English (India) (male).'},
    {'id': 'en-IE-ConnorNeural', 'name': 'Edge · Connor (en-IE)', 'language': 'en', 'description': 'Microsoft Connor Online (Natural) - English (Ireland) (male).'},
    {'id': 'en-IE-EmilyNeural', 'name': 'Edge · Emily (en-IE)', 'language': 'en', 'description': 'Microsoft Emily Online (Natural) - English (Ireland) (female).'},
    {'id': 'en-KE-AsiliaNeural', 'name': 'Edge · Asilia (en-KE)', 'language': 'en', 'description': 'Microsoft Asilia Online (Natural) - English (Kenya) (female).'},
    {'id': 'en-KE-ChilembaNeural', 'name': 'Edge · Chilemba (en-KE)', 'language': 'en', 'description': 'Microsoft Chilemba Online (Natural) - English (Kenya) (male).'},
    {'id': 'en-NZ-MitchellNeural', 'name': 'Edge · Mitchell (en-NZ)', 'language': 'en', 'description': 'Microsoft Mitchell Online (Natural) - English (New Zealand) (male).'},
    {'id': 'en-NZ-MollyNeural', 'name': 'Edge · Molly (en-NZ)', 'language': 'en', 'description': 'Microsoft Molly Online (Natural) - English (New Zealand) (female).'},
    {'id': 'en-NG-AbeoNeural', 'name': 'Edge · Abeo (en-NG)', 'language': 'en', 'description': 'Microsoft Abeo Online (Natural) - English (Nigeria) (male).'},
    {'id': 'en-NG-EzinneNeural', 'name': 'Edge · Ezinne (en-NG)', 'language': 'en', 'description': 'Microsoft Ezinne Online (Natural) - English (Nigeria) (female).'},
    {'id': 'en-PH-JamesNeural', 'name': 'Edge · James (en-PH)', 'language': 'en', 'description': 'Microsoft James Online (Natural) - English (Philippines) (male).'},
    {'id': 'en-PH-RosaNeural', 'name': 'Edge · Rosa (en-PH)', 'language': 'en', 'description': 'Microsoft Rosa Online (Natural) - English (Philippines) (female).'},
    {'id': 'en-US-AvaNeural', 'name': 'Edge · Ava (en-US)', 'language': 'en', 'description': 'Microsoft Ava Online (Natural) - English (United States) (female).'},
    {'id': 'en-US-AndrewNeural', 'name': 'Edge · Andrew (en-US)', 'language': 'en', 'description': 'Microsoft Andrew Online (Natural) - English (United States) (male).'},
    {'id': 'en-US-EmmaNeural', 'name': 'Edge · Emma (en-US)', 'language': 'en', 'description': 'Microsoft Emma Online (Natural) - English (United States) (female).'},
    {'id': 'en-US-BrianNeural', 'name': 'Edge · Brian (en-US)', 'language': 'en', 'description': 'Microsoft Brian Online (Natural) - English (United States) (male).'},
    {'id': 'en-SG-LunaNeural', 'name': 'Edge · Luna (en-SG)', 'language': 'en', 'description': 'Microsoft Luna Online (Natural) - English (Singapore) (female).'},
    {'id': 'en-SG-WayneNeural', 'name': 'Edge · Wayne (en-SG)', 'language': 'en', 'description': 'Microsoft Wayne Online (Natural) - English (Singapore) (male).'},
    {'id': 'en-ZA-LeahNeural', 'name': 'Edge · Leah (en-ZA)', 'language': 'en', 'description': 'Microsoft Leah Online (Natural) - English (South Africa) (female).'},
    {'id': 'en-ZA-LukeNeural', 'name': 'Edge · Luke (en-ZA)', 'language': 'en', 'description': 'Microsoft Luke Online (Natural) - English (South Africa) (male).'},
    {'id': 'en-TZ-ElimuNeural', 'name': 'Edge · Elimu (en-TZ)', 'language': 'en', 'description': 'Microsoft Elimu Online (Natural) - English (Tanzania) (male).'},
    {'id': 'en-TZ-ImaniNeural', 'name': 'Edge · Imani (en-TZ)', 'language': 'en', 'description': 'Microsoft Imani Online (Natural) - English (Tanzania) (female).'},
    {'id': 'en-GB-LibbyNeural', 'name': 'Edge · Libby (en-GB)', 'language': 'en', 'description': 'Microsoft Libby Online (Natural) - English (United Kingdom) (female).'},
    {'id': 'en-GB-MaisieNeural', 'name': 'Edge · Maisie (en-GB)', 'language': 'en', 'description': 'Microsoft Maisie Online (Natural) - English (United Kingdom) (female).'},
    {'id': 'en-GB-RyanNeural', 'name': 'Edge · Ryan (en-GB)', 'language': 'en', 'description': 'Microsoft Ryan Online (Natural) - English (United Kingdom) (male).'},
    {'id': 'en-GB-SoniaNeural', 'name': 'Edge · Sonia (en-GB)', 'language': 'en', 'description': 'Microsoft Sonia Online (Natural) - English (United Kingdom) (female).'},
    {'id': 'en-GB-ThomasNeural', 'name': 'Edge · Thomas (en-GB)', 'language': 'en', 'description': 'Microsoft Thomas Online (Natural) - English (United Kingdom) (male).'},
    {'id': 'en-US-AnaNeural', 'name': 'Edge · Ana (en-US)', 'language': 'en', 'description': 'Microsoft Ana Online (Natural) - English (United States) (female).'},
    {'id': 'en-US-AndrewMultilingualNeural', 'name': 'Edge · AndrewMultilingual (en-US)', 'language': 'en', 'description': 'Microsoft AndrewMultilingual Online (Natural) - English (United States) (male).'},
    {'id': 'en-US-AriaNeural', 'name': 'Edge · Aria (en-US)', 'language': 'en', 'description': 'Microsoft Aria Online (Natural) - English (United States) (female).'},
    {'id': 'en-US-AvaMultilingualNeural', 'name': 'Edge · AvaMultilingual (en-US)', 'language': 'en', 'description': 'Microsoft AvaMultilingual Online (Natural) - English (United States) (female).'},
    {'id': 'en-US-BrianMultilingualNeural', 'name': 'Edge · BrianMultilingual (en-US)', 'language': 'en', 'description': 'Microsoft BrianMultilingual Online (Natural) - English (United States) (male).'},
    {'id': 'en-US-ChristopherNeural', 'name': 'Edge · Christopher (en-US)', 'language': 'en', 'description': 'Microsoft Christopher Online (Natural) - English (United States) (male).'},
    {'id': 'en-US-EmmaMultilingualNeural', 'name': 'Edge · EmmaMultilingual (en-US)', 'language': 'en', 'description': 'Microsoft EmmaMultilingual Online (Natural) - English (United States) (female).'},
    {'id': 'en-US-EricNeural', 'name': 'Edge · Eric (en-US)', 'language': 'en', 'description': 'Microsoft Eric Online (Natural) - English (United States) (male).'},
    {'id': 'en-US-GuyNeural', 'name': 'Edge · Guy (en-US)', 'language': 'en', 'description': 'Microsoft Guy Online (Natural) - English (United States) (male).'},
    {'id': 'en-US-JennyNeural', 'name': 'Edge · Jenny (en-US)', 'language': 'en', 'description': 'Microsoft Jenny Online (Natural) - English (United States) (female).'},
    {'id': 'en-US-MichelleNeural', 'name': 'Edge · Michelle (en-US)', 'language': 'en', 'description': 'Microsoft Michelle Online (Natural) - English (United States) (female).'},
    {'id': 'en-US-RogerNeural', 'name': 'Edge · Roger (en-US)', 'language': 'en', 'description': 'Microsoft Roger Online (Natural) - English (United States) (male).'},
    {'id': 'en-US-SteffanNeural', 'name': 'Edge · Steffan (en-US)', 'language': 'en', 'description': 'Microsoft Steffan Online (Natural) - English (United States) (male).'},
    {'id': 'et-EE-AnuNeural', 'name': 'Edge · Anu (et-EE)', 'language': 'et', 'description': 'Microsoft Anu Online (Natural) - Estonian (Estonia) (female).'},
    {'id': 'et-EE-KertNeural', 'name': 'Edge · Kert (et-EE)', 'language': 'et', 'description': 'Microsoft Kert Online (Natural) - Estonian (Estonia) (male).'},
    {'id': 'fil-PH-AngeloNeural', 'name': 'Edge · Angelo (fil-PH)', 'language': 'fil', 'description': 'Microsoft Angelo Online (Natural) - Filipino (Philippines) (male).'},
    {'id': 'fil-PH-BlessicaNeural', 'name': 'Edge · Blessica (fil-PH)', 'language': 'fil', 'description': 'Microsoft Blessica Online (Natural) - Filipino (Philippines) (female).'},
    {'id': 'fi-FI-HarriNeural', 'name': 'Edge · Harri (fi-FI)', 'language': 'fi', 'description': 'Microsoft Harri Online (Natural) - Finnish (Finland) (male).'},
    {'id': 'fi-FI-NooraNeural', 'name': 'Edge · Noora (fi-FI)', 'language': 'fi', 'description': 'Microsoft Noora Online (Natural) - Finnish (Finland) (female).'},
    {'id': 'fr-BE-CharlineNeural', 'name': 'Edge · Charline (fr-BE)', 'language': 'fr', 'description': 'Microsoft Charline Online (Natural) - French (Belgium) (female).'},
    {'id': 'fr-BE-GerardNeural', 'name': 'Edge · Gerard (fr-BE)', 'language': 'fr', 'description': 'Microsoft Gerard Online (Natural) - French (Belgium) (male).'},
    {'id': 'fr-CA-ThierryNeural', 'name': 'Edge · Thierry (fr-CA)', 'language': 'fr', 'description': 'Microsoft Thierry Online (Natural) - French (Canada) (male).'},
    {'id': 'fr-CA-AntoineNeural', 'name': 'Edge · Antoine (fr-CA)', 'language': 'fr', 'description': 'Microsoft Antoine Online (Natural) - French (Canada) (male).'},
    {'id': 'fr-CA-JeanNeural', 'name': 'Edge · Jean (fr-CA)', 'language': 'fr', 'description': 'Microsoft Jean Online (Natural) - French (Canada) (male).'},
    {'id': 'fr-CA-SylvieNeural', 'name': 'Edge · Sylvie (fr-CA)', 'language': 'fr', 'description': 'Microsoft Sylvie Online (Natural) - French (Canada) (female).'},
    {'id': 'fr-FR-VivienneMultilingualNeural', 'name': 'Edge · VivienneMultilingual (fr-FR)', 'language': 'fr', 'description': 'Microsoft VivienneMultilingual Online (Natural) - French (France) (female).'},
    {'id': 'fr-FR-RemyMultilingualNeural', 'name': 'Edge · RemyMultilingual (fr-FR)', 'language': 'fr', 'description': 'Microsoft RemyMultilingual Online (Natural) - French (France) (male).'},
    {'id': 'fr-FR-DeniseNeural', 'name': 'Edge · Denise (fr-FR)', 'language': 'fr', 'description': 'Microsoft Denise Online (Natural) - French (France) (female).'},
    {'id': 'fr-FR-EloiseNeural', 'name': 'Edge · Eloise (fr-FR)', 'language': 'fr', 'description': 'Microsoft Eloise Online (Natural) - French (France) (female).'},
    {'id': 'fr-FR-HenriNeural', 'name': 'Edge · Henri (fr-FR)', 'language': 'fr', 'description': 'Microsoft Henri Online (Natural) - French (France) (male).'},
    {'id': 'fr-CH-ArianeNeural', 'name': 'Edge · Ariane (fr-CH)', 'language': 'fr', 'description': 'Microsoft Ariane Online (Natural) - French (Switzerland) (female).'},
    {'id': 'fr-CH-FabriceNeural', 'name': 'Edge · Fabrice (fr-CH)', 'language': 'fr', 'description': 'Microsoft Fabrice Online (Natural) - French (Switzerland) (male).'},
    {'id': 'gl-ES-RoiNeural', 'name': 'Edge · Roi (gl-ES)', 'language': 'gl', 'description': 'Microsoft Roi Online (Natural) - Galician (male).'},
    {'id': 'gl-ES-SabelaNeural', 'name': 'Edge · Sabela (gl-ES)', 'language': 'gl', 'description': 'Microsoft Sabela Online (Natural) - Galician (female).'},
    {'id': 'ka-GE-EkaNeural', 'name': 'Edge · Eka (ka-GE)', 'language': 'ka', 'description': 'Microsoft Eka Online (Natural) - Georgian (Georgia) (female).'},
    {'id': 'ka-GE-GiorgiNeural', 'name': 'Edge · Giorgi (ka-GE)', 'language': 'ka', 'description': 'Microsoft Giorgi Online (Natural) - Georgian (Georgia) (male).'},
    {'id': 'de-AT-IngridNeural', 'name': 'Edge · Ingrid (de-AT)', 'language': 'de', 'description': 'Microsoft Ingrid Online (Natural) - German (Austria) (female).'},
    {'id': 'de-AT-JonasNeural', 'name': 'Edge · Jonas (de-AT)', 'language': 'de', 'description': 'Microsoft Jonas Online (Natural) - German (Austria) (male).'},
    {'id': 'de-DE-SeraphinaMultilingualNeural', 'name': 'Edge · SeraphinaMultilingual (de-DE)', 'language': 'de', 'description': 'Microsoft SeraphinaMultilingual Online (Natural) - German (Germany) (female).'},
    {'id': 'de-DE-FlorianMultilingualNeural', 'name': 'Edge · FlorianMultilingual (de-DE)', 'language': 'de', 'description': 'Microsoft FlorianMultilingual Online (Natural) - German (Germany) (male).'},
    {'id': 'de-DE-AmalaNeural', 'name': 'Edge · Amala (de-DE)', 'language': 'de', 'description': 'Microsoft Amala Online (Natural) - German (Germany) (female).'},
    {'id': 'de-DE-ConradNeural', 'name': 'Edge · Conrad (de-DE)', 'language': 'de', 'description': 'Microsoft Conrad Online (Natural) - German (Germany) (male).'},
    {'id': 'de-DE-KatjaNeural', 'name': 'Edge · Katja (de-DE)', 'language': 'de', 'description': 'Microsoft Katja Online (Natural) - German (Germany) (female).'},
    {'id': 'de-DE-KillianNeural', 'name': 'Edge · Killian (de-DE)', 'language': 'de', 'description': 'Microsoft Killian Online (Natural) - German (Germany) (male).'},
    {'id': 'de-CH-JanNeural', 'name': 'Edge · Jan (de-CH)', 'language': 'de', 'description': 'Microsoft Jan Online (Natural) - German (Switzerland) (male).'},
    {'id': 'de-CH-LeniNeural', 'name': 'Edge · Leni (de-CH)', 'language': 'de', 'description': 'Microsoft Leni Online (Natural) - German (Switzerland) (female).'},
    {'id': 'el-GR-AthinaNeural', 'name': 'Edge · Athina (el-GR)', 'language': 'el', 'description': 'Microsoft Athina Online (Natural) - Greek (Greece) (female).'},
    {'id': 'el-GR-NestorasNeural', 'name': 'Edge · Nestoras (el-GR)', 'language': 'el', 'description': 'Microsoft Nestoras Online (Natural) - Greek (Greece) (male).'},
    {'id': 'gu-IN-DhwaniNeural', 'name': 'Edge · Dhwani (gu-IN)', 'language': 'gu', 'description': 'Microsoft Dhwani Online (Natural) - Gujarati (India) (female).'},
    {'id': 'gu-IN-NiranjanNeural', 'name': 'Edge · Niranjan (gu-IN)', 'language': 'gu', 'description': 'Microsoft Niranjan Online (Natural) - Gujarati (India) (male).'},
    {'id': 'he-IL-AvriNeural', 'name': 'Edge · Avri (he-IL)', 'language': 'he', 'description': 'Microsoft Avri Online (Natural) - Hebrew (Israel) (male).'},
    {'id': 'he-IL-HilaNeural', 'name': 'Edge · Hila (he-IL)', 'language': 'he', 'description': 'Microsoft Hila Online (Natural) - Hebrew (Israel) (female).'},
    {'id': 'hi-IN-MadhurNeural', 'name': 'Edge · Madhur (hi-IN)', 'language': 'hi', 'description': 'Microsoft Madhur Online (Natural) - Hindi (India) (male).'},
    {'id': 'hi-IN-SwaraNeural', 'name': 'Edge · Swara (hi-IN)', 'language': 'hi', 'description': 'Microsoft Swara Online (Natural) - Hindi (India) (female).'},
    {'id': 'hu-HU-NoemiNeural', 'name': 'Edge · Noemi (hu-HU)', 'language': 'hu', 'description': 'Microsoft Noemi Online (Natural) - Hungarian (Hungary) (female).'},
    {'id': 'hu-HU-TamasNeural', 'name': 'Edge · Tamas (hu-HU)', 'language': 'hu', 'description': 'Microsoft Tamas Online (Natural) - Hungarian (Hungary) (male).'},
    {'id': 'is-IS-GudrunNeural', 'name': 'Edge · Gudrun (is-IS)', 'language': 'is', 'description': 'Microsoft Gudrun Online (Natural) - Icelandic (Iceland) (female).'},
    {'id': 'is-IS-GunnarNeural', 'name': 'Edge · Gunnar (is-IS)', 'language': 'is', 'description': 'Microsoft Gunnar Online (Natural) - Icelandic (Iceland) (male).'},
    {'id': 'id-ID-ArdiNeural', 'name': 'Edge · Ardi (id-ID)', 'language': 'id', 'description': 'Microsoft Ardi Online (Natural) - Indonesian (Indonesia) (male).'},
    {'id': 'id-ID-GadisNeural', 'name': 'Edge · Gadis (id-ID)', 'language': 'id', 'description': 'Microsoft Gadis Online (Natural) - Indonesian (Indonesia) (female).'},
    {'id': 'iu-Latn-CA-SiqiniqNeural', 'name': 'Edge · Siqiniq (iu-Latn-CA)', 'language': 'iu', 'description': 'Microsoft Siqiniq Online (Natural) - Inuktitut (Latin, Canada) (female).'},
    {'id': 'iu-Latn-CA-TaqqiqNeural', 'name': 'Edge · Taqqiq (iu-Latn-CA)', 'language': 'iu', 'description': 'Microsoft Taqqiq Online (Natural) - Inuktitut (Latin, Canada) (male).'},
    {'id': 'iu-Cans-CA-SiqiniqNeural', 'name': 'Edge · Siqiniq (iu-Cans-CA)', 'language': 'iu', 'description': 'Microsoft Siqiniq Online (Natural) - Inuktitut (Syllabics, Canada) (female).'},
    {'id': 'iu-Cans-CA-TaqqiqNeural', 'name': 'Edge · Taqqiq (iu-Cans-CA)', 'language': 'iu', 'description': 'Microsoft Taqqiq Online (Natural) - Inuktitut (Syllabics, Canada) (male).'},
    {'id': 'ga-IE-ColmNeural', 'name': 'Edge · Colm (ga-IE)', 'language': 'ga', 'description': 'Microsoft Colm Online (Natural) - Irish (Ireland) (male).'},
    {'id': 'ga-IE-OrlaNeural', 'name': 'Edge · Orla (ga-IE)', 'language': 'ga', 'description': 'Microsoft Orla Online (Natural) - Irish (Ireland) (female).'},
    {'id': 'it-IT-GiuseppeMultilingualNeural', 'name': 'Edge · GiuseppeMultilingual (it-IT)', 'language': 'it', 'description': 'Microsoft GiuseppeMultilingual Online (Natural) - Italian (Italy) (male).'},
    {'id': 'it-IT-DiegoNeural', 'name': 'Edge · Diego (it-IT)', 'language': 'it', 'description': 'Microsoft Diego Online (Natural) - Italian (Italy) (male).'},
    {'id': 'it-IT-ElsaNeural', 'name': 'Edge · Elsa (it-IT)', 'language': 'it', 'description': 'Microsoft Elsa Online (Natural) - Italian (Italy) (female).'},
    {'id': 'it-IT-IsabellaNeural', 'name': 'Edge · Isabella (it-IT)', 'language': 'it', 'description': 'Microsoft Isabella Online (Natural) - Italian (Italy) (female).'},
    {'id': 'ja-JP-KeitaNeural', 'name': 'Edge · Keita (ja-JP)', 'language': 'ja', 'description': 'Microsoft Keita Online (Natural) - Japanese (Japan) (male).'},
    {'id': 'ja-JP-NanamiNeural', 'name': 'Edge · Nanami (ja-JP)', 'language': 'ja', 'description': 'Microsoft Nanami Online (Natural) - Japanese (Japan) (female).'},
    {'id': 'jv-ID-DimasNeural', 'name': 'Edge · Dimas (jv-ID)', 'language': 'jv', 'description': 'Microsoft Dimas Online (Natural) - Javanese (Indonesia) (male).'},
    {'id': 'jv-ID-SitiNeural', 'name': 'Edge · Siti (jv-ID)', 'language': 'jv', 'description': 'Microsoft Siti Online (Natural) - Javanese (Indonesia) (female).'},
    {'id': 'kn-IN-GaganNeural', 'name': 'Edge · Gagan (kn-IN)', 'language': 'kn', 'description': 'Microsoft Gagan Online (Natural) - Kannada (India) (male).'},
    {'id': 'kn-IN-SapnaNeural', 'name': 'Edge · Sapna (kn-IN)', 'language': 'kn', 'description': 'Microsoft Sapna Online (Natural) - Kannada (India) (female).'},
    {'id': 'kk-KZ-AigulNeural', 'name': 'Edge · Aigul (kk-KZ)', 'language': 'kk', 'description': 'Microsoft Aigul Online (Natural) - Kazakh (Kazakhstan) (female).'},
    {'id': 'kk-KZ-DauletNeural', 'name': 'Edge · Daulet (kk-KZ)', 'language': 'kk', 'description': 'Microsoft Daulet Online (Natural) - Kazakh (Kazakhstan) (male).'},
    {'id': 'km-KH-PisethNeural', 'name': 'Edge · Piseth (km-KH)', 'language': 'km', 'description': 'Microsoft Piseth Online (Natural) - Khmer (Cambodia) (male).'},
    {'id': 'km-KH-SreymomNeural', 'name': 'Edge · Sreymom (km-KH)', 'language': 'km', 'description': 'Microsoft Sreymom Online (Natural) - Khmer (Cambodia) (female).'},
    {'id': 'ko-KR-HyunsuMultilingualNeural', 'name': 'Edge · HyunsuMultilingual (ko-KR)', 'language': 'ko', 'description': 'Microsoft HyunsuMultilingual Online (Natural) - Korean (Korea) (male).'},
    {'id': 'ko-KR-InJoonNeural', 'name': 'Edge · InJoon (ko-KR)', 'language': 'ko', 'description': 'Microsoft InJoon Online (Natural) - Korean (Korea) (male).'},
    {'id': 'ko-KR-SunHiNeural', 'name': 'Edge · SunHi (ko-KR)', 'language': 'ko', 'description': 'Microsoft SunHi Online (Natural) - Korean (Korea) (female).'},
    {'id': 'lo-LA-ChanthavongNeural', 'name': 'Edge · Chanthavong (lo-LA)', 'language': 'lo', 'description': 'Microsoft Chanthavong Online (Natural) - Lao (Laos) (male).'},
    {'id': 'lo-LA-KeomanyNeural', 'name': 'Edge · Keomany (lo-LA)', 'language': 'lo', 'description': 'Microsoft Keomany Online (Natural) - Lao (Laos) (female).'},
    {'id': 'lv-LV-EveritaNeural', 'name': 'Edge · Everita (lv-LV)', 'language': 'lv', 'description': 'Microsoft Everita Online (Natural) - Latvian (Latvia) (female).'},
    {'id': 'lv-LV-NilsNeural', 'name': 'Edge · Nils (lv-LV)', 'language': 'lv', 'description': 'Microsoft Nils Online (Natural) - Latvian (Latvia) (male).'},
    {'id': 'lt-LT-LeonasNeural', 'name': 'Edge · Leonas (lt-LT)', 'language': 'lt', 'description': 'Microsoft Leonas Online (Natural) - Lithuanian (Lithuania) (male).'},
    {'id': 'lt-LT-OnaNeural', 'name': 'Edge · Ona (lt-LT)', 'language': 'lt', 'description': 'Microsoft Ona Online (Natural) - Lithuanian (Lithuania) (female).'},
    {'id': 'mk-MK-AleksandarNeural', 'name': 'Edge · Aleksandar (mk-MK)', 'language': 'mk', 'description': 'Microsoft Aleksandar Online (Natural) - Macedonian (North Macedonia) (male).'},
    {'id': 'mk-MK-MarijaNeural', 'name': 'Edge · Marija (mk-MK)', 'language': 'mk', 'description': 'Microsoft Marija Online (Natural) - Macedonian (North Macedonia) (female).'},
    {'id': 'ms-MY-OsmanNeural', 'name': 'Edge · Osman (ms-MY)', 'language': 'ms', 'description': 'Microsoft Osman Online (Natural) - Malay (Malaysia) (male).'},
    {'id': 'ms-MY-YasminNeural', 'name': 'Edge · Yasmin (ms-MY)', 'language': 'ms', 'description': 'Microsoft Yasmin Online (Natural) - Malay (Malaysia) (female).'},
    {'id': 'ml-IN-MidhunNeural', 'name': 'Edge · Midhun (ml-IN)', 'language': 'ml', 'description': 'Microsoft Midhun Online (Natural) - Malayalam (India) (male).'},
    {'id': 'ml-IN-SobhanaNeural', 'name': 'Edge · Sobhana (ml-IN)', 'language': 'ml', 'description': 'Microsoft Sobhana Online (Natural) - Malayalam (India) (female).'},
    {'id': 'mt-MT-GraceNeural', 'name': 'Edge · Grace (mt-MT)', 'language': 'mt', 'description': 'Microsoft Grace Online (Natural) - Maltese (Malta) (female).'},
    {'id': 'mt-MT-JosephNeural', 'name': 'Edge · Joseph (mt-MT)', 'language': 'mt', 'description': 'Microsoft Joseph Online (Natural) - Maltese (Malta) (male).'},
    {'id': 'mr-IN-AarohiNeural', 'name': 'Edge · Aarohi (mr-IN)', 'language': 'mr', 'description': 'Microsoft Aarohi Online (Natural) - Marathi (India) (female).'},
    {'id': 'mr-IN-ManoharNeural', 'name': 'Edge · Manohar (mr-IN)', 'language': 'mr', 'description': 'Microsoft Manohar Online (Natural) - Marathi (India) (male).'},
    {'id': 'mn-MN-BataaNeural', 'name': 'Edge · Bataa (mn-MN)', 'language': 'mn', 'description': 'Microsoft Bataa Online (Natural) - Mongolian (Mongolia) (male).'},
    {'id': 'mn-MN-YesuiNeural', 'name': 'Edge · Yesui (mn-MN)', 'language': 'mn', 'description': 'Microsoft Yesui Online (Natural) - Mongolian (Mongolia) (female).'},
    {'id': 'ne-NP-HemkalaNeural', 'name': 'Edge · Hemkala (ne-NP)', 'language': 'ne', 'description': 'Microsoft Hemkala Online (Natural) - Nepali (Nepal) (female).'},
    {'id': 'ne-NP-SagarNeural', 'name': 'Edge · Sagar (ne-NP)', 'language': 'ne', 'description': 'Microsoft Sagar Online (Natural) - Nepali (Nepal) (male).'},
    {'id': 'nb-NO-FinnNeural', 'name': 'Edge · Finn (nb-NO)', 'language': 'nb', 'description': 'Microsoft Finn Online (Natural) - Norwegian (Bokmål Norway) (male).'},
    {'id': 'nb-NO-PernilleNeural', 'name': 'Edge · Pernille (nb-NO)', 'language': 'nb', 'description': 'Microsoft Pernille Online (Natural) - Norwegian (Bokmål, Norway) (female).'},
    {'id': 'ps-AF-GulNawazNeural', 'name': 'Edge · GulNawaz (ps-AF)', 'language': 'ps', 'description': 'Microsoft GulNawaz Online (Natural) - Pashto (Afghanistan) (male).'},
    {'id': 'ps-AF-LatifaNeural', 'name': 'Edge · Latifa (ps-AF)', 'language': 'ps', 'description': 'Microsoft Latifa Online (Natural) - Pashto (Afghanistan) (female).'},
    {'id': 'fa-IR-DilaraNeural', 'name': 'Edge · Dilara (fa-IR)', 'language': 'fa', 'description': 'Microsoft Dilara Online (Natural) - Persian (Iran) (female).'},
    {'id': 'fa-IR-FaridNeural', 'name': 'Edge · Farid (fa-IR)', 'language': 'fa', 'description': 'Microsoft Farid Online (Natural) - Persian (Iran) (male).'},
    {'id': 'pl-PL-MarekNeural', 'name': 'Edge · Marek (pl-PL)', 'language': 'pl', 'description': 'Microsoft Marek Online (Natural) - Polish (Poland) (male).'},
    {'id': 'pl-PL-ZofiaNeural', 'name': 'Edge · Zofia (pl-PL)', 'language': 'pl', 'description': 'Microsoft Zofia Online (Natural) - Polish (Poland) (female).'},
    {'id': 'pt-BR-ThalitaMultilingualNeural', 'name': 'Edge · ThalitaMultilingual (pt-BR)', 'language': 'pt', 'description': 'Microsoft ThalitaMultilingual Online (Natural) - Portuguese (Brazil) (female).'},
    {'id': 'pt-BR-AntonioNeural', 'name': 'Edge · Antonio (pt-BR)', 'language': 'pt', 'description': 'Microsoft Antonio Online (Natural) - Portuguese (Brazil) (male).'},
    {'id': 'pt-BR-FranciscaNeural', 'name': 'Edge · Francisca (pt-BR)', 'language': 'pt', 'description': 'Microsoft Francisca Online (Natural) - Portuguese (Brazil) (female).'},
    {'id': 'pt-PT-DuarteNeural', 'name': 'Edge · Duarte (pt-PT)', 'language': 'pt', 'description': 'Microsoft Duarte Online (Natural) - Portuguese (Portugal) (male).'},
    {'id': 'pt-PT-RaquelNeural', 'name': 'Edge · Raquel (pt-PT)', 'language': 'pt', 'description': 'Microsoft Raquel Online (Natural) - Portuguese (Portugal) (female).'},
    {'id': 'ro-RO-AlinaNeural', 'name': 'Edge · Alina (ro-RO)', 'language': 'ro', 'description': 'Microsoft Alina Online (Natural) - Romanian (Romania) (female).'},
    {'id': 'ro-RO-EmilNeural', 'name': 'Edge · Emil (ro-RO)', 'language': 'ro', 'description': 'Microsoft Emil Online (Natural) - Romanian (Romania) (male).'},
    {'id': 'ru-RU-DmitryNeural', 'name': 'Edge · Dmitry (ru-RU)', 'language': 'ru', 'description': 'Microsoft Dmitry Online (Natural) - Russian (Russia) (male).'},
    {'id': 'ru-RU-SvetlanaNeural', 'name': 'Edge · Svetlana (ru-RU)', 'language': 'ru', 'description': 'Microsoft Svetlana Online (Natural) - Russian (Russia) (female).'},
    {'id': 'sr-RS-NicholasNeural', 'name': 'Edge · Nicholas (sr-RS)', 'language': 'sr', 'description': 'Microsoft Nicholas Online (Natural) - Serbian (Serbia) (male).'},
    {'id': 'sr-RS-SophieNeural', 'name': 'Edge · Sophie (sr-RS)', 'language': 'sr', 'description': 'Microsoft Sophie Online (Natural) - Serbian (Serbia) (female).'},
    {'id': 'si-LK-SameeraNeural', 'name': 'Edge · Sameera (si-LK)', 'language': 'si', 'description': 'Microsoft Sameera Online (Natural) - Sinhala (Sri Lanka) (male).'},
    {'id': 'si-LK-ThiliniNeural', 'name': 'Edge · Thilini (si-LK)', 'language': 'si', 'description': 'Microsoft Thilini Online (Natural) - Sinhala (Sri Lanka) (female).'},
    {'id': 'sk-SK-LukasNeural', 'name': 'Edge · Lukas (sk-SK)', 'language': 'sk', 'description': 'Microsoft Lukas Online (Natural) - Slovak (Slovakia) (male).'},
    {'id': 'sk-SK-ViktoriaNeural', 'name': 'Edge · Viktoria (sk-SK)', 'language': 'sk', 'description': 'Microsoft Viktoria Online (Natural) - Slovak (Slovakia) (female).'},
    {'id': 'sl-SI-PetraNeural', 'name': 'Edge · Petra (sl-SI)', 'language': 'sl', 'description': 'Microsoft Petra Online (Natural) - Slovenian (Slovenia) (female).'},
    {'id': 'sl-SI-RokNeural', 'name': 'Edge · Rok (sl-SI)', 'language': 'sl', 'description': 'Microsoft Rok Online (Natural) - Slovenian (Slovenia) (male).'},
    {'id': 'so-SO-MuuseNeural', 'name': 'Edge · Muuse (so-SO)', 'language': 'so', 'description': 'Microsoft Muuse Online (Natural) - Somali (Somalia) (male).'},
    {'id': 'so-SO-UbaxNeural', 'name': 'Edge · Ubax (so-SO)', 'language': 'so', 'description': 'Microsoft Ubax Online (Natural) - Somali (Somalia) (female).'},
    {'id': 'es-AR-ElenaNeural', 'name': 'Edge · Elena (es-AR)', 'language': 'es', 'description': 'Microsoft Elena Online (Natural) - Spanish (Argentina) (female).'},
    {'id': 'es-AR-TomasNeural', 'name': 'Edge · Tomas (es-AR)', 'language': 'es', 'description': 'Microsoft Tomas Online (Natural) - Spanish (Argentina) (male).'},
    {'id': 'es-BO-MarceloNeural', 'name': 'Edge · Marcelo (es-BO)', 'language': 'es', 'description': 'Microsoft Marcelo Online (Natural) - Spanish (Bolivia) (male).'},
    {'id': 'es-BO-SofiaNeural', 'name': 'Edge · Sofia (es-BO)', 'language': 'es', 'description': 'Microsoft Sofia Online (Natural) - Spanish (Bolivia) (female).'},
    {'id': 'es-CL-CatalinaNeural', 'name': 'Edge · Catalina (es-CL)', 'language': 'es', 'description': 'Microsoft Catalina Online (Natural) - Spanish (Chile) (female).'},
    {'id': 'es-CL-LorenzoNeural', 'name': 'Edge · Lorenzo (es-CL)', 'language': 'es', 'description': 'Microsoft Lorenzo Online (Natural) - Spanish (Chile) (male).'},
    {'id': 'es-CO-GonzaloNeural', 'name': 'Edge · Gonzalo (es-CO)', 'language': 'es', 'description': 'Microsoft Gonzalo Online (Natural) - Spanish (Colombia) (male).'},
    {'id': 'es-CO-SalomeNeural', 'name': 'Edge · Salome (es-CO)', 'language': 'es', 'description': 'Microsoft Salome Online (Natural) - Spanish (Colombia) (female).'},
    {'id': 'es-ES-XimenaNeural', 'name': 'Edge · Ximena (es-ES)', 'language': 'es', 'description': 'Microsoft Ximena Online (Natural) - Spanish (Colombia) (female).'},
    {'id': 'es-CR-JuanNeural', 'name': 'Edge · Juan (es-CR)', 'language': 'es', 'description': 'Microsoft Juan Online (Natural) - Spanish (Costa Rica) (male).'},
    {'id': 'es-CR-MariaNeural', 'name': 'Edge · Maria (es-CR)', 'language': 'es', 'description': 'Microsoft Maria Online (Natural) - Spanish (Costa Rica) (female).'},
    {'id': 'es-CU-BelkysNeural', 'name': 'Edge · Belkys (es-CU)', 'language': 'es', 'description': 'Microsoft Belkys Online (Natural) - Spanish (Cuba) (female).'},
    {'id': 'es-CU-ManuelNeural', 'name': 'Edge · Manuel (es-CU)', 'language': 'es', 'description': 'Microsoft Manuel Online (Natural) - Spanish (Cuba) (male).'},
    {'id': 'es-DO-EmilioNeural', 'name': 'Edge · Emilio (es-DO)', 'language': 'es', 'description': 'Microsoft Emilio Online (Natural) - Spanish (Dominican Republic) (male).'},
    {'id': 'es-DO-RamonaNeural', 'name': 'Edge · Ramona (es-DO)', 'language': 'es', 'description': 'Microsoft Ramona Online (Natural) - Spanish (Dominican Republic) (female).'},
    {'id': 'es-EC-AndreaNeural', 'name': 'Edge · Andrea (es-EC)', 'language': 'es', 'description': 'Microsoft Andrea Online (Natural) - Spanish (Ecuador) (female).'},
    {'id': 'es-EC-LuisNeural', 'name': 'Edge · Luis (es-EC)', 'language': 'es', 'description': 'Microsoft Luis Online (Natural) - Spanish (Ecuador) (male).'},
    {'id': 'es-SV-LorenaNeural', 'name': 'Edge · Lorena (es-SV)', 'language': 'es', 'description': 'Microsoft Lorena Online (Natural) - Spanish (El Salvador) (female).'},
    {'id': 'es-SV-RodrigoNeural', 'name': 'Edge · Rodrigo (es-SV)', 'language': 'es', 'description': 'Microsoft Rodrigo Online (Natural) - Spanish (El Salvador) (male).'},
    {'id': 'es-GQ-JavierNeural', 'name': 'Edge · Javier (es-GQ)', 'language': 'es', 'description': 'Microsoft Javier Online (Natural) - Spanish (Equatorial Guinea) (male).'},
    {'id': 'es-GQ-TeresaNeural', 'name': 'Edge · Teresa (es-GQ)', 'language': 'es', 'description': 'Microsoft Teresa Online (Natural) - Spanish (Equatorial Guinea) (female).'},
    {'id': 'es-GT-AndresNeural', 'name': 'Edge · Andres (es-GT)', 'language': 'es', 'description': 'Microsoft Andres Online (Natural) - Spanish (Guatemala) (male).'},
    {'id': 'es-GT-MartaNeural', 'name': 'Edge · Marta (es-GT)', 'language': 'es', 'description': 'Microsoft Marta Online (Natural) - Spanish (Guatemala) (female).'},
    {'id': 'es-HN-CarlosNeural', 'name': 'Edge · Carlos (es-HN)', 'language': 'es', 'description': 'Microsoft Carlos Online (Natural) - Spanish (Honduras) (male).'},
    {'id': 'es-HN-KarlaNeural', 'name': 'Edge · Karla (es-HN)', 'language': 'es', 'description': 'Microsoft Karla Online (Natural) - Spanish (Honduras) (female).'},
    {'id': 'es-MX-DaliaNeural', 'name': 'Edge · Dalia (es-MX)', 'language': 'es', 'description': 'Microsoft Dalia Online (Natural) - Spanish (Mexico) (female).'},
    {'id': 'es-MX-JorgeNeural', 'name': 'Edge · Jorge (es-MX)', 'language': 'es', 'description': 'Microsoft Jorge Online (Natural) - Spanish (Mexico) (male).'},
    {'id': 'es-NI-FedericoNeural', 'name': 'Edge · Federico (es-NI)', 'language': 'es', 'description': 'Microsoft Federico Online (Natural) - Spanish (Nicaragua) (male).'},
    {'id': 'es-NI-YolandaNeural', 'name': 'Edge · Yolanda (es-NI)', 'language': 'es', 'description': 'Microsoft Yolanda Online (Natural) - Spanish (Nicaragua) (female).'},
    {'id': 'es-PA-MargaritaNeural', 'name': 'Edge · Margarita (es-PA)', 'language': 'es', 'description': 'Microsoft Margarita Online (Natural) - Spanish (Panama) (female).'},
    {'id': 'es-PA-RobertoNeural', 'name': 'Edge · Roberto (es-PA)', 'language': 'es', 'description': 'Microsoft Roberto Online (Natural) - Spanish (Panama) (male).'},
    {'id': 'es-PY-MarioNeural', 'name': 'Edge · Mario (es-PY)', 'language': 'es', 'description': 'Microsoft Mario Online (Natural) - Spanish (Paraguay) (male).'},
    {'id': 'es-PY-TaniaNeural', 'name': 'Edge · Tania (es-PY)', 'language': 'es', 'description': 'Microsoft Tania Online (Natural) - Spanish (Paraguay) (female).'},
    {'id': 'es-PE-AlexNeural', 'name': 'Edge · Alex (es-PE)', 'language': 'es', 'description': 'Microsoft Alex Online (Natural) - Spanish (Peru) (male).'},
    {'id': 'es-PE-CamilaNeural', 'name': 'Edge · Camila (es-PE)', 'language': 'es', 'description': 'Microsoft Camila Online (Natural) - Spanish (Peru) (female).'},
    {'id': 'es-PR-KarinaNeural', 'name': 'Edge · Karina (es-PR)', 'language': 'es', 'description': 'Microsoft Karina Online (Natural) - Spanish (Puerto Rico) (female).'},
    {'id': 'es-PR-VictorNeural', 'name': 'Edge · Victor (es-PR)', 'language': 'es', 'description': 'Microsoft Victor Online (Natural) - Spanish (Puerto Rico) (male).'},
    {'id': 'es-ES-AlvaroNeural', 'name': 'Edge · Alvaro (es-ES)', 'language': 'es', 'description': 'Microsoft Alvaro Online (Natural) - Spanish (Spain) (male).'},
    {'id': 'es-ES-ElviraNeural', 'name': 'Edge · Elvira (es-ES)', 'language': 'es', 'description': 'Microsoft Elvira Online (Natural) - Spanish (Spain) (female).'},
    {'id': 'es-US-AlonsoNeural', 'name': 'Edge · Alonso (es-US)', 'language': 'es', 'description': 'Microsoft Alonso Online (Natural) - Spanish (United States) (male).'},
    {'id': 'es-US-PalomaNeural', 'name': 'Edge · Paloma (es-US)', 'language': 'es', 'description': 'Microsoft Paloma Online (Natural) - Spanish (United States) (female).'},
    {'id': 'es-UY-MateoNeural', 'name': 'Edge · Mateo (es-UY)', 'language': 'es', 'description': 'Microsoft Mateo Online (Natural) - Spanish (Uruguay) (male).'},
    {'id': 'es-UY-ValentinaNeural', 'name': 'Edge · Valentina (es-UY)', 'language': 'es', 'description': 'Microsoft Valentina Online (Natural) - Spanish (Uruguay) (female).'},
    {'id': 'es-VE-PaolaNeural', 'name': 'Edge · Paola (es-VE)', 'language': 'es', 'description': 'Microsoft Paola Online (Natural) - Spanish (Venezuela) (female).'},
    {'id': 'es-VE-SebastianNeural', 'name': 'Edge · Sebastian (es-VE)', 'language': 'es', 'description': 'Microsoft Sebastian Online (Natural) - Spanish (Venezuela) (male).'},
    {'id': 'su-ID-JajangNeural', 'name': 'Edge · Jajang (su-ID)', 'language': 'su', 'description': 'Microsoft Jajang Online (Natural) - Sundanese (Indonesia) (male).'},
    {'id': 'su-ID-TutiNeural', 'name': 'Edge · Tuti (su-ID)', 'language': 'su', 'description': 'Microsoft Tuti Online (Natural) - Sundanese (Indonesia) (female).'},
    {'id': 'sw-KE-RafikiNeural', 'name': 'Edge · Rafiki (sw-KE)', 'language': 'sw', 'description': 'Microsoft Rafiki Online (Natural) - Swahili (Kenya) (male).'},
    {'id': 'sw-KE-ZuriNeural', 'name': 'Edge · Zuri (sw-KE)', 'language': 'sw', 'description': 'Microsoft Zuri Online (Natural) - Swahili (Kenya) (female).'},
    {'id': 'sw-TZ-DaudiNeural', 'name': 'Edge · Daudi (sw-TZ)', 'language': 'sw', 'description': 'Microsoft Daudi Online (Natural) - Swahili (Tanzania) (male).'},
    {'id': 'sw-TZ-RehemaNeural', 'name': 'Edge · Rehema (sw-TZ)', 'language': 'sw', 'description': 'Microsoft Rehema Online (Natural) - Swahili (Tanzania) (female).'},
    {'id': 'sv-SE-MattiasNeural', 'name': 'Edge · Mattias (sv-SE)', 'language': 'sv', 'description': 'Microsoft Mattias Online (Natural) - Swedish (Sweden) (male).'},
    {'id': 'sv-SE-SofieNeural', 'name': 'Edge · Sofie (sv-SE)', 'language': 'sv', 'description': 'Microsoft Sofie Online (Natural) - Swedish (Sweden) (female).'},
    {'id': 'ta-IN-PallaviNeural', 'name': 'Edge · Pallavi (ta-IN)', 'language': 'ta', 'description': 'Microsoft Pallavi Online (Natural) - Tamil (India) (female).'},
    {'id': 'ta-IN-ValluvarNeural', 'name': 'Edge · Valluvar (ta-IN)', 'language': 'ta', 'description': 'Microsoft Valluvar Online (Natural) - Tamil (India) (male).'},
    {'id': 'ta-MY-KaniNeural', 'name': 'Edge · Kani (ta-MY)', 'language': 'ta', 'description': 'Microsoft Kani Online (Natural) - Tamil (Malaysia) (female).'},
    {'id': 'ta-MY-SuryaNeural', 'name': 'Edge · Surya (ta-MY)', 'language': 'ta', 'description': 'Microsoft Surya Online (Natural) - Tamil (Malaysia) (male).'},
    {'id': 'ta-SG-AnbuNeural', 'name': 'Edge · Anbu (ta-SG)', 'language': 'ta', 'description': 'Microsoft Anbu Online (Natural) - Tamil (Singapore) (male).'},
    {'id': 'ta-SG-VenbaNeural', 'name': 'Edge · Venba (ta-SG)', 'language': 'ta', 'description': 'Microsoft Venba Online (Natural) - Tamil (Singapore) (female).'},
    {'id': 'ta-LK-KumarNeural', 'name': 'Edge · Kumar (ta-LK)', 'language': 'ta', 'description': 'Microsoft Kumar Online (Natural) - Tamil (Sri Lanka) (male).'},
    {'id': 'ta-LK-SaranyaNeural', 'name': 'Edge · Saranya (ta-LK)', 'language': 'ta', 'description': 'Microsoft Saranya Online (Natural) - Tamil (Sri Lanka) (female).'},
    {'id': 'te-IN-MohanNeural', 'name': 'Edge · Mohan (te-IN)', 'language': 'te', 'description': 'Microsoft Mohan Online (Natural) - Telugu (India) (male).'},
    {'id': 'te-IN-ShrutiNeural', 'name': 'Edge · Shruti (te-IN)', 'language': 'te', 'description': 'Microsoft Shruti Online (Natural) - Telugu (India) (female).'},
    {'id': 'th-TH-NiwatNeural', 'name': 'Edge · Niwat (th-TH)', 'language': 'th', 'description': 'Microsoft Niwat Online (Natural) - Thai (Thailand) (male).'},
    {'id': 'th-TH-PremwadeeNeural', 'name': 'Edge · Premwadee (th-TH)', 'language': 'th', 'description': 'Microsoft Premwadee Online (Natural) - Thai (Thailand) (female).'},
    {'id': 'tr-TR-EmelNeural', 'name': 'Edge · Emel (tr-TR)', 'language': 'tr', 'description': 'Microsoft Emel Online (Natural) - Turkish (Turkey) (female).'},
    {'id': 'tr-TR-AhmetNeural', 'name': 'Edge · Ahmet (tr-TR)', 'language': 'tr', 'description': 'Microsoft Ahmet Online (Natural) - Turkish (Türkiye) (male).'},
    {'id': 'uk-UA-OstapNeural', 'name': 'Edge · Ostap (uk-UA)', 'language': 'uk', 'description': 'Microsoft Ostap Online (Natural) - Ukrainian (Ukraine) (male).'},
    {'id': 'uk-UA-PolinaNeural', 'name': 'Edge · Polina (uk-UA)', 'language': 'uk', 'description': 'Microsoft Polina Online (Natural) - Ukrainian (Ukraine) (female).'},
    {'id': 'ur-IN-GulNeural', 'name': 'Edge · Gul (ur-IN)', 'language': 'ur', 'description': 'Microsoft Gul Online (Natural) - Urdu (India) (female).'},
    {'id': 'ur-IN-SalmanNeural', 'name': 'Edge · Salman (ur-IN)', 'language': 'ur', 'description': 'Microsoft Salman Online (Natural) - Urdu (India) (male).'},
    {'id': 'ur-PK-AsadNeural', 'name': 'Edge · Asad (ur-PK)', 'language': 'ur', 'description': 'Microsoft Asad Online (Natural) - Urdu (Pakistan) (male).'},
    {'id': 'ur-PK-UzmaNeural', 'name': 'Edge · Uzma (ur-PK)', 'language': 'ur', 'description': 'Microsoft Uzma Online (Natural) - Urdu (Pakistan) (female).'},
    {'id': 'uz-UZ-MadinaNeural', 'name': 'Edge · Madina (uz-UZ)', 'language': 'uz', 'description': 'Microsoft Madina Online (Natural) - Uzbek (Uzbekistan) (female).'},
    {'id': 'uz-UZ-SardorNeural', 'name': 'Edge · Sardor (uz-UZ)', 'language': 'uz', 'description': 'Microsoft Sardor Online (Natural) - Uzbek (Uzbekistan) (male).'},
    {'id': 'vi-VN-HoaiMyNeural', 'name': 'Edge · HoaiMy (vi-VN)', 'language': 'vi', 'description': 'Microsoft HoaiMy Online (Natural) - Vietnamese (Vietnam) (female).'},
    {'id': 'vi-VN-NamMinhNeural', 'name': 'Edge · NamMinh (vi-VN)', 'language': 'vi', 'description': 'Microsoft NamMinh Online (Natural) - Vietnamese (Vietnam) (male).'},
    {'id': 'cy-GB-AledNeural', 'name': 'Edge · Aled (cy-GB)', 'language': 'cy', 'description': 'Microsoft Aled Online (Natural) - Welsh (United Kingdom) (male).'},
    {'id': 'cy-GB-NiaNeural', 'name': 'Edge · Nia (cy-GB)', 'language': 'cy', 'description': 'Microsoft Nia Online (Natural) - Welsh (United Kingdom) (female).'},
    {'id': 'zu-ZA-ThandoNeural', 'name': 'Edge · Thando (zu-ZA)', 'language': 'zu', 'description': 'Microsoft Thando Online (Natural) - Zulu (South Africa) (female).'},
    {'id': 'zu-ZA-ThembaNeural', 'name': 'Edge · Themba (zu-ZA)', 'language': 'zu', 'description': 'Microsoft Themba Online (Natural) - Zulu (South Africa) (male).'},
)

PIPER_VOICE = {
    "id": None,
    "name": "Piper · Lessac (US English)",
    "language": "en",
    "description": "Piper en_US Lessac medium, the default offline voice.",
}

